Fixes #1910: apoc.meta.stats return false relationship count when having multi-labeled nodes
vga91/neo4j-apoc-procedures pull request #100
Opened 2021-07-05 15:08 UTC by vga91

Fixes #1910

The problem is that `TokenRead.labelCount()` and `TokenRead.relationshipTypeCount()` returns all labels/relTypes (even those deleted).
For consistency with the other results, we should return only labels/relTypes in use.

2021-07-06 12:58 UTC, conker84 commented on core/src/test/java/apoc/meta/MetaTest.java
> +    public void testMetaStatsWithLabelAndRelTypeCountInUse() {
questo test non l'ho capito me lo puoi spiegare?

2021-07-06 13:02 UTC, vga91 commented on core/src/test/java/apoc/meta/MetaTest.java
> +    public void testMetaStatsWithLabelAndRelTypeCountInUse() {
Qui vado a creare dei nodi e relazioni e faccio la `apoc.meta.stats`. 
Poi ne cancello alcuni, rifaccio la `apoc.meta.stats`, e verifico che i risultati siano cambiati (ovvero diminuiti).
Come stava prima anche cancellando entità, `labelCount` e `relTypeCount` non cambiavano anche se cancellavo tutte le entità con quella label / tipo relazione.

2021-07-06 13:05 UTC, conker84 commented on core/src/test/java/apoc/meta/MetaTest.java
> +    public void testMetaStatsWithLabelAndRelTypeCountInUse() {
io mi sarò cecato ma non vedo la cancellazione

2021-07-06 13:05 UTC, conker84 commented on core/src/test/java/apoc/meta/MetaTest.java
> +    public void testMetaStatsWithLabelAndRelTypeCountInUse() {
si infatti mi sono cecato

2021-07-06 13:06 UTC, conker84 requested changes

2021-07-06 13:06 UTC, conker84 commented on core/src/test/java/apoc/meta/MetaTest.java
> +            assertEquals(2L, row.get("labelCount"));
testiamo anche i tipi?

2021-07-06 13:06 UTC, conker84 commented on core/src/test/java/apoc/meta/MetaTest.java
> +            assertEquals(4L, row.get("labelCount"));
testiamo anche i tipi

2021-07-14 13:37 UTC, vga91 commented on core/src/test/java/apoc/meta/MetaTest.java
> +            assertEquals(2L, row.get("labelCount"));
aggiunto

2021-07-14 13:37 UTC, vga91 commented on core/src/test/java/apoc/meta/MetaTest.java
> +            assertEquals(4L, row.get("labelCount"));
aggiunto

2021-07-19 13:55 UTC, conker84 approved these changes

2021-07-19 13:55 UTC, conker84 commented
Ok sottomettilo

2021-07-20 07:32 UTC, closed without merging