Issue 1630
vga91/neo4j-apoc-procedures pull request #11
Opened 2020-11-11 13:22 UTC by vga91

Fixes #1630

One sentence summary of the change.

## Proposed Changes (Mandatory)

A brief list of proposed changes in order to fix the issue:

- Added support to do a basic auth in apoc.load.csv with an url like `http://user:password@host`
- Added `apoc.load.csvParams` similarly to `apoc.load.jsonParams` procedure
- Added tests in `LoadCsvTest.java` to cover cases of the related issue
- Moved `extractCredentialsIfNeeded(url, failOnError)` common method from `LoadJson.java` to `Util.java`
- Added tests in `LoadJsonTest.java` to cover same cases of the issue
- Added `readerFor(String fileName, Map<String, Object> headers, String payload)` method in `FileUtils.java`

2020-11-11 15:28 UTC, conker84 requested changes

2020-11-11 15:28 UTC, conker84 commented on core/src/test/java/apoc/load/LoadJsonTest.java
> +                                .withBody("{ result: 'message' }")
fai così salva il messaggio in una hashmap, dopo di che qui la metti serializzata con jackson e a linea 290 invece controlli che le mappe di input e output siano uguali

2020-11-11 15:28 UTC, conker84 commented on full/src/test/java/apoc/load/LoadCsvTest.java
> +                                .withBody("headFoo,headBar\n" + "one,two\n" + "three,four\n" + "five,six\n")
Anche qui fai una lista di mappe e poi trasformala in stringa e usala per controllare i valori sotto

2020-11-11 15:28 UTC, conker84 commented on full/src/main/java/apoc/load/LoadCsv.java
> +    @Description("apoc.load.csvParams('url', {httpHeader: value}, payload, {config}) YIELD lineNo, list, map - load from CSV URL (e.g. web-api) while sending headers / payload to load CSV from URL as
scusa perché questa nuova procedura?

2020-11-11 16:17 UTC, vga91 commented on full/src/main/java/apoc/load/LoadCsv.java
> +    @Description("apoc.load.csvParams('url', {httpHeader: value}, payload, {config}) YIELD lineNo, list, map - load from CSV URL (e.g. web-api) while sending headers / payload to load CSV from URL as
Sia leggendo la issue che il commento di Michael, ho inteso che oltre a mettere la possibilità di mettere la basic auth partendo da `http://user:password@host` bisogna rendere il comportamento con gli Url remoti consistente con la apoc.load.json, ossia che se voglio caricare un json su un server che richiede un header o un payload (ad esempio per il metodo 'POST') viene richiamata la `apoc.load.jsonParams(...)`.

2020-11-12 11:01 UTC, conker84 requested changes

2020-11-12 11:01 UTC, conker84 commented on full/src/test/java/apoc/load/LoadCsvTest.java
> +                                .withBody("headFoo,headBar\n" + "one,two\n" + "three,four\n" + "five,six\n")
qua ti sei scordato di fare la stessa cosa di sopra?

2020-11-12 11:40 UTC, vga91 commented on full/src/test/java/apoc/load/LoadCsvTest.java
> +                                .withBody("headFoo,headBar\n" + "one,two\n" + "three,four\n" + "five,six\n")
Sì qui non l'ho messo perché non sapevo se andava bene o meno la `apoc.load.csvParams()`. Ora lo faccio anche qui

2020-11-22 18:02 UTC, conker84 commented on full/src/main/java/apoc/load/LoadCsv.java
> +    @Description("apoc.load.csvParams('url', {httpHeader: value}, payload, {config}) YIELD lineNo, list, map - load from CSV URL (e.g. web-api) while sending headers / payload to load CSV from URL as
@vga91 per favore questo aggiungilo nel commento della PR quando la fai su neo4j

2020-11-22 18:02 UTC, conker84 approved these changes

2020-11-23 22:21 UTC, closed without merging