Fixes #963: Possibly allow custom mapping for map of values
vga91/neo4j-apoc-procedures pull request #113
Opened 2021-08-03 10:16 UTC by vga91

WIP (docs, tests,...)

2022-02-07 17:05 UTC, conker84 requested changes

2022-02-07 17:05 UTC, conker84 commented on core/src/main/java/apoc/export/csv/CsvLoaderConfig.java
> +    public CsvLoaderConfig(Builder builder) {
perché? no di solito si fa un metodo statico... e questo dovrebbe restare provate

2022-02-07 17:05 UTC, conker84 commented on core/src/main/java/apoc/load/AbstractMapping.java
> +    abstract protected Object convert(Object input);
è necessario? non si può usare `commonConvertType` rinominandolo `convert`? Poi nelle sottoclassi eventualmente gli fai l'override e lo richiami con `super`

2022-02-07 17:05 UTC, conker84 commented on core/src/main/java/apoc/load/CsvMapping.java
> +        if (type == Meta.Types.STRING) return value;
questo secondo me non è necessario

2022-02-07 17:05 UTC, conker84 commented on core/src/main/java/apoc/load/CsvMapping.java
> +    }
secondo quello che ti ho scritto sopra sull'usare `commonConvertType` questo verrebbe cosi:
```suggestion
    public Object convert(Object value) {
        final String stringValue = (String) value;
        return array 
                ? convertArray(stringValue, arrayPattern, this::convertType) 
                : super.convert(stringValue);
    }
```

2022-02-07 17:05 UTC, conker84 commented on core/src/main/java/apoc/load/CsvMapping.java
> +        if (type == Meta.Types.STRING) return value;
Tra l'altro perché `array` è gestito solo qui e non negli altri? se ho delle stringhe che voglio convertire in array?

2022-02-07 17:05 UTC, conker84 commented on core/src/main/java/apoc/load/LoadJsonConfig.java
> +                : mapValue.entrySet()
```suggestion
        if (mapValue == null) return null;
        return mapValue.entrySet()
```

2022-02-07 17:05 UTC, conker84 commented on core/src/main/java/apoc/load/Xml.java
> +                elementMap.put("ignore", true);
cosa vuol dire?

2022-02-07 17:05 UTC, conker84 commented on core/src/main/java/apoc/load/util/LoadCsvConfig.java
> +        mappings = createMapping(null);
?

2022-02-07 17:05 UTC, conker84 commented on core/src/main/java/apoc/util/MappingUtil.java
> +public class MappingUtil {
Forse è il caso di vedere se in `Util.java` già ci sono metodi simili, in caso negativo sposta questi li

2022-02-07 17:05 UTC, conker84 commented on core/src/test/java/apoc/load/LoadJsonTest.java
> +    public void testLoadJsonWithMapping2() {
per favore nominiamolo meglio

2022-02-07 17:05 UTC, conker84 commented on core/src/test/java/apoc/load/LoadJsonTest.java
> +    public void testLoadJsonWithMappingAndPath() {
non ho capito a che serve?

2022-02-07 17:05 UTC, conker84 commented on core/src/test/java/apoc/load/XmlTest.java
> +
Qui non si testa nulla?!

2022-02-07 17:05 UTC, conker84 commented on core/src/test/java/apoc/load/XmlTest.java
> +    public void testLoadXmlWithNextWordRelsWithNewConfigOptions1() {
perché l'uno finale? nominiamolo meglio

2022-02-07 17:05 UTC, conker84 commented on full/src/main/java/apoc/load/Jdbc.java
> +                            .atZone(ZoneId.of(config.getZoneId()))
scusa non si può mettere dentro il config come prima?

2022-02-07 17:05 UTC, conker84 commented on full/src/main/java/apoc/load/Jdbc.java
> +                            .atZone(ZoneId.of(config.getZoneId()))
come sopra

2022-02-07 17:05 UTC, conker84 commented on full/src/main/java/apoc/load/Jdbc.java
> +            }
non ho capito? non c'è modo di farlo via Types?
Di chi è `UUID`?

2022-02-07 17:05 UTC, conker84 commented on full/src/test/java/apoc/gephi/GephiTest.java
> +        db.executeTransactionally("create (a:Author {country: 'Iceland'})-");
No aspe non ho capito questo test perché lo hai modificato

2022-02-08 14:12 UTC, vga91 commented on core/src/main/java/apoc/load/CsvMapping.java
> +        if (type == Meta.Types.STRING) return value;
Sì, qui e su `XlsMapping` lo gestisco perché veniva fatto già in precedenza tramite `arraySep`.
Sugli altri infatti ho messo un `// todo - evaluate if might be worth using a convertArray() like CsvMapping`,
ora lo implemento anche sugli altri

2022-02-09 10:45 UTC, vga91 commented on core/src/test/java/apoc/load/LoadJsonTest.java
> +    public void testLoadJsonWithMappingAndPath() {
Per testare che anche mettendo il parametro `path`, ovvero il secondo parametro della `apoc.load.json(..)`,
il mapping funziona lo stesso correttamente

2022-02-09 10:47 UTC, vga91 commented on core/src/test/java/apoc/load/XmlTest.java
> +
Sì scusa, in realtà dovevo cancellarlo perché è una ripetizione del test di sopra. Mo lo tolgo

2022-02-09 11:04 UTC, vga91 commented on full/src/main/java/apoc/load/Jdbc.java
> +            }
Sì, l'ho messo qui perché prima c'era un `if (value instanceof UUID || value instanceof BigInteger || value instanceof BigDecimal) {` , adesso lo tolgo perché in effetti posso gestire tramite il `Mapping` generico

2022-02-09 15:35 UTC, vga91 commented on core/src/main/java/apoc/load/util/LoadCsvConfig.java
> +        mappings = createMapping(null);
Qui è null perché riprendo il `public abstract Object createMapping(I input);` di LoadImportConfig, però effettivamente in questo caso non mi serve niente come input perché sta tutto dentro il `this`.

2022-02-09 15:38 UTC, vga91 commented on core/src/main/java/apoc/load/Xml.java
> +                elementMap.put("ignore", true);
Se metto questo "ignore" poi non fa il `stack.addLast(elementMap);` a riga 242, che è quello che scrive il risultato, perché c'è un `elementMap.containsKey("ignore")`. Mi è sembrata la cosa meno invasiva da fare

2022-02-09 15:41 UTC, vga91 commented on full/src/test/java/apoc/gephi/GephiTest.java
> +        db.executeTransactionally("create (a:Author {country: 'Iceland'})-");
Devo aver fatto qualche casino mentre stavo facendo una rebase :X, resettato

2024-03-01 09:21 UTC, vga91 commented
core issue, chiudo per ora

2024-03-01 09:21 UTC, closed without merging