apoc.uuid.install not setting uuid on new nodes
vga91/neo4j-apoc-procedures pull request #114
Opened 2021-08-04 09:11 UTC by vga91

Issue 2137

2021-09-30 16:03 UTC, conker84 requested changes

2021-09-30 16:03 UTC, conker84 commented on full/src/main/java/apoc/uuid/UuidHandler.java
> +                    Pair.of(SystemPropertyKeys.addToSetLabel.name(), config.isAddToSetLabels())
no mettilo come proprietà esterna come fatto in TransactionHandler

2021-10-25 07:36 UTC, vga91 commented on full/src/main/java/apoc/uuid/UuidHandler.java
> +                    Pair.of(SystemPropertyKeys.addToSetLabel.name(), config.isAddToSetLabels())
Scusa, questo non mi è chiaro, cosa intendi?

2021-10-25 08:43 UTC, conker84 commented on full/src/main/java/apoc/uuid/UuidHandler.java
> +                    Pair.of(SystemPropertyKeys.addToSetLabel.name(), config.isAddToSetLabels())
Se metti questa property qui diventa chiave del nodo quindi se cambi la configurazione lui crea un nuovo nodo, invece deve aggiornare il vecchio

2024-02-27 09:04 UTC, vga91 commented
Fixed `https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/2350`

2024-02-27 09:04 UTC, closed without merging