Issue 577: return apoc.nodes.count(['User'])
vga91/neo4j-apoc-procedures pull request #128
Opened 2021-09-17 12:38 UTC by vga91

Issue 577 (in `Meta.java` because of `MetaConfig`)

2021-10-25 10:37 UTC, conker84 requested changes

2021-10-25 10:37 UTC, conker84 commented on core/src/main/java/apoc/meta/Meta.java
> +    }
Prova così per favore

```suggestion
    @UserFunction(name = "apoc.meta.nodes.count")
    @Description("apoc.meta.nodes.count([labels], $config) - Returns the sum of the nodes with a label present in the list.")
    public long count(@Name(value = "nodes", defaultValue = "[]") List<String> nodes, @Name(value = "config", defaultValue = "{}") Map<String, Object> config) {
        MetaConfig conf = new MetaConfig(config);

        final DatabaseSubGraph subGraph = new DatabaseSubGraph(transaction);
        Stream<Label> labels = CollectionUtils.isEmpty(nodes)
                ? StreamSupport.stream(subGraph.getAllLabelsInUse().spliterator(), false)
                : nodes.stream().filter(Objects::nonNull).map(String::trim).map(Label::label);
        
        final boolean isIncludeRels = CollectionUtils.isEmpty(conf.getIncludesRels());

        Set<Long> visitedNodes = new HashSet<>();

        return labels
                .flatMap(label -> isIncludeRels ? Stream.of(subGraph.countsForNode(label)) : conf.getIncludesRels()
                .stream()
                .filter(Objects::nonNull)
                .map(String::trim)
                .map(rel -> Pair.of(rel.charAt(0), rel.substring(1)))
                .flatMap(pair -> {
                    final Direction direction;
                    switch (pair.first()) {
                        case '>':
                            direction = Direction.OUTGOING;
                            break;
                        case '<':
                            direction = Direction.INCOMING;
                            break;
                        default:
                            direction = Direction.BOTH;
                    }
                    return transaction.findNodes(label)
                            .map(node -> {
                                if (!visitedNodes.contains(node.getId()) && node.hasRelationship(direction, RelationshipType.withName(pair.other()))) {
                                    visitedNodes.add(node.getId());
                                    return 1L;
                                } else {
                                    return 0L;
                                }
                            })
                            .stream();
                }))
                .reduce(0L, Math::addExact);
    }
```

2021-10-25 12:35 UTC, vga91 commented on core/src/main/java/apoc/meta/Meta.java
> +    }
> Prova così per favore

L'ho cambiato un po' rispetto a quello suggerito, perché per come sta fatto nel caso venga passato un config con un `rels: ['MY_COUNT_REL']` con il secondo argomento del `Pair.of(...)` toglieva la prima lettera.
Per come l'hai scritta è inteso che il carattere per definire la direzione è il primo, ad esempio `>MY_COUNT_REL`, io invece l'ho fatto al contrario (cioè nell'ultimo carattere, ad esempio `MY_COUNT_REL>`) per seguire quello detto nel commento di Michael sulla issue, ma volendo posso cambiarlo

2021-11-03 11:51 UTC, conker84 commented on core/src/main/java/apoc/meta/Meta.java
> +    }
Ah si bravissimo!!!!

2021-11-03 12:19 UTC, closed without merging