Issue 2239: Provide query statistics for apoc.merge functions
vga91/neo4j-apoc-procedures pull request #139
Opened 2021-10-12 10:48 UTC by vga91

Issue 2239

Added `merge` version with `stats` column.

2021-11-02 17:13 UTC, conker84 requested changes

2021-11-02 17:13 UTC, conker84 commented on core/src/main/java/apoc/result/ObjectNodeResult.java
> +public class ObjectNodeResult extends NodeResult {
```suggestion
public class NodeResultWithStats extends NodeResult {
```

2021-11-02 17:13 UTC, conker84 commented on core/src/main/java/apoc/merge/Merge.java
> +                        "RETURN r";
possiamo rimetterlo come prima?

2021-11-02 17:13 UTC, conker84 commented on core/src/main/java/apoc/result/ObjectRelationshipResult.java
> +public class ObjectRelationshipResult extends RelationshipResult {
```suggestion
public class RelationshipResultWithStats extends RelationshipResult {
```

2021-11-02 17:13 UTC, conker84 commented on core/src/main/java/apoc/result/ObjectNodeResult.java
> + */
questi no eliminali anche dall'altro

2021-11-02 17:13 UTC, conker84 commented on core/src/main/java/apoc/merge/Merge.java
> +        return tx.execute(cypher, params);
magari ci puoi aggiungere:
```suggestion
        return tx.execute(cypher, params).columnAs("n");
```

2021-11-02 17:13 UTC, conker84 commented on core/src/main/java/apoc/merge/Merge.java
> +        return tx.execute(cypher, params);
```suggestion
        return tx.execute(cypher, params).columnAs("r");
```

2021-11-02 17:13 UTC, conker84 commented on core/src/main/java/apoc/merge/Merge.java
>      @Description("\"apoc.merge.node.eager(['Label'], identProps:{key:value, ...}, onCreateProps:{key:value,...}, onMatchProps:{key:value,...}}) - merge nodes with dynamic labels, with support for set
so che non c'entra nulla ma per favore correggi la descrizione qui
```suggestion
    @Description("\"apoc.merge.node(['Label'], identProps:{key:value, ...}, onCreateProps:{key:value,...}, onMatchProps:{key:value,...}}) - merge nodes with dynamic labels, with support for setting properties ON CREATE or ON MATCH")
```

2021-11-03 08:24 UTC, vga91 commented on core/src/main/java/apoc/merge/Merge.java
> +        return tx.execute(cypher, params);
Per com'è fatto, ho bisogno di ritornare `Result` dal metodo, perché poi lo utilizzo per fare `nodeResult.getQueryStatistics()` alla riga 64

2021-11-03 08:25 UTC, vga91 commented on core/src/main/java/apoc/merge/Merge.java
> +        return tx.execute(cypher, params);
Come sopra (mi serve per usare `relResult.getQueryStatistics()`)

2021-12-28 11:49 UTC, conker84 commented on core/src/main/java/apoc/merge/Merge.java
> +        return tx.execute(cypher, params);
Ok

2021-12-28 11:51 UTC, conker84 approved these changes
Questa va bene l'unica cosa prima di sottometterla rimuovi tutta la parte di documentazione inutile e lascia solo quella necessaria

2022-01-03 08:36 UTC, closed without merging