Issue 1014: apoc.export.cypher.all violates unique constraint when rewriting nodes at the same time
vga91/neo4j-apoc-procedures pull request #149
Opened 2021-11-02 08:31 UTC by vga91

Issue 1014

2021-11-03 10:41 UTC, conker84 approved these changes

2021-11-03 10:41 UTC, conker84 commented on core/src/main/java/apoc/export/cypher/ExportCypher.java
> +        }
Manca la parte dove fai la release del lock

2021-11-03 10:41 UTC, conker84 requested changes

2021-11-03 10:41 UTC, conker84 commented on core/src/main/java/apoc/export/cypher/ExportCypher.java
> +        }
Manca la parte dove fai la release del lock

2024-03-01 09:20 UTC, vga91 commented
Issue closed

2024-03-01 09:20 UTC, closed without merging