Fixes #1568: apoc.custom.list displays procedure name but execution errors out with
vga91/neo4j-apoc-procedures pull request #17
Opened 2020-11-25 11:37 UTC by vga91

Fixes neo4j-contrib#1568

WIP: looking for other possible cases

2020-12-09 15:13 UTC, vga91 commented on src/main/java/apoc/custom/CypherProcedures.java
> +        new CustomProcedureStorage(Pools.NEO4J_SCHEDULER, api, log).restoreProceduresSync();
Qui ho lasciato il metodo non statico perché poi vado a richiamare un altro metodo non statico già esistente, il `restoreProcedures()`

2021-01-14 09:14 UTC, conker84 requested changes

2021-01-14 09:14 UTC, conker84 commented on src/test/java/apoc/custom/CypherProceduresTest.java
> +    @Test()
```suggestion
    @Test
```

2021-01-14 09:14 UTC, conker84 commented on src/main/java/apoc/custom/CypherProcedures.java
> +    @Procedure(value = "apoc.custom.restore")
```suggestion
    @Procedure(value = "apoc.custom.refresh")
```

2021-01-14 09:14 UTC, conker84 commented on src/main/java/apoc/custom/CypherProcedures.java
> +        new CustomProcedureStorage(Pools.NEO4J_SCHEDULER, api, log).restoreProceduresSync();
fallo statico

2021-01-21 09:58 UTC, closed without merging