Issue 1714
vga91/neo4j-apoc-procedures pull request #24
Opened 2021-01-15 09:19 UTC by vga91

WIP

2021-01-18 15:44 UTC, conker84 requested changes

2021-01-18 15:44 UTC, conker84 commented on full/src/main/java/apoc/custom/CypherProceduresHandler.java
> +                                if (outType.getClass().equals(Neo4jTypes.MapType.class)) return ValueUtils.of(row);
perché sei sicuro? strano che sia diverso da sopra

2021-01-21 11:11 UTC, vga91 commented on full/src/main/java/apoc/custom/CypherProceduresHandler.java
> +                                if (outType.getClass().equals(Neo4jTypes.MapType.class)) return ValueUtils.of(row);
Perché il risultato dovrebbe restituire una mappa solo se il tipo è esattamente `MapType`, 
mentre se è un `NodeType / RelationshipType`, anche se estendono `MapType` il risultato dovrebbe essere `{Nodo_Risultante}` e non `{t: {Nodo_Risultante}}`

2021-01-21 12:57 UTC, conker84 commented on full/src/main/java/apoc/custom/CypherProceduresHandler.java
> +                                if (outType.getClass().equals(Neo4jTypes.MapType.class)) return ValueUtils.of(row);
Non credo sia corretto così

2021-01-28 11:53 UTC, conker84 requested changes

2021-01-28 11:53 UTC, conker84 commented on core/src/main/antlr/apoc/custom/Signature.g4
> +IDENTIFIER:	[a-zA-Z_][a-zA-Z0-9_]* ;
fai revert di questo e dentro Singatures a linea 134 aggiungi questa linea:

`if (ns == null) throw new IllegalStateException("Unsupported procedure name, the procedure must have at least two chars ");`

e cambia i test di conseguenza

2021-02-01 11:40 UTC, conker84 requested changes

2021-02-01 11:40 UTC, conker84 commented on full/src/test/java/apoc/custom/CypherProceduresTest.java
> +        db.executeTransactionally("CALL apoc.custom.asFunction('ret_node_list', 'MATCH (t:Target {value : $val}) RETURN t', 'LIST OF NODE', [['val', 'INTEGER']])");
questo non torna una lista di nodi o mi sbaglio?

2021-02-01 11:40 UTC, conker84 commented on full/src/test/java/apoc/custom/CypherProceduresTest.java
> +        db.executeTransactionally("CALL apoc.custom.asFunction('ret_map_list', 'MATCH (t:Target {value : $val}) RETURN t', 'LIST OF MAP', [['val', 'INTEGER']])");
questo non torna una lista di mappe o mi sbaglio?

2021-02-01 11:54 UTC, vga91 commented on full/src/test/java/apoc/custom/CypherProceduresTest.java
> +        db.executeTransactionally("CALL apoc.custom.asFunction('ret_node_list', 'MATCH (t:Target {value : $val}) RETURN t', 'LIST OF NODE', [['val', 'INTEGER']])");
Sì, la `RETURN custom.ret_node_list(2) AS val` come risultato torna:
```
[
  {
  "t": {
   "identity": 1,
   "labels": [...],
   "properties": {...}
  }
]
```
così come la `RETURN custom.ret_map_list(2) AS val`.

Mentre facendo quella che ritorna i nodi, `RETURN custom.ret_node_list(2) AS val` ritorna il risultato senza wrappare con l'array

2021-02-01 11:56 UTC, vga91 commented on full/src/test/java/apoc/custom/CypherProceduresTest.java
> +        db.executeTransactionally("CALL apoc.custom.asFunction('ret_map_list', 'MATCH (t:Target {value : $val}) RETURN t', 'LIST OF MAP', [['val', 'INTEGER']])");
come sopra

2021-02-01 16:23 UTC, closed without merging