Fixes #1657: apoc.schema.assert nodekey throws EquivalentSchemaRuleAlreadyExistsException
vga91/neo4j-apoc-procedures pull request #27
Opened 2021-01-20 20:58 UTC by vga91

Fixes #1657

2021-01-21 08:59 UTC, conker84 requested changes

2021-01-21 08:59 UTC, conker84 commented on core/src/main/java/apoc/schema/Schemas.java
> +                if (item instanceof String) {
scusa ma se `Map<String, List<Object>> constraints` allora item come fa ad essere `String`???????????????

2021-01-21 08:59 UTC, conker84 commented on core/src/main/java/apoc/schema/Schemas.java
> +                    return info.keys.equals(item);
Se `info.keys` e `item` non contengono doppioni (credo di no) fai cosi:
```suggestion
                    Set<Object> keys = new HashSet<>(info.keys);
                    Set<Object> items = new HashSet<>(items);
                    return keys.equals(item);
```

2021-01-21 08:59 UTC, conker84 commented on core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
> +        testResult(session, "CALL apoc.schema.assert(null,{Foo:[['baa','baz']]})", (result) -> {
perché hai aggiunto questo qui?

2021-01-21 09:15 UTC, vga91 commented on core/src/main/java/apoc/schema/Schemas.java
> +                if (item instanceof String) {
Perché faccio prima `constraints.get(label)` e quindi mi restituisce una `List<Object>`, che poi ciclo con il removeIf

2021-01-21 10:48 UTC, vga91 commented on core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
> +        testResult(session, "CALL apoc.schema.assert(null,{Foo:[['baa','baz']]})", (result) -> {
Per controllare che, con l'ultimo parametro non specificato (quindi a true), cancelli il vecchio constraint solo se diverso da quello dell'assert, mentre se è uguale rimane con KEPT, similmente a quanto avviene nel `testKeepSchema()` di `SchemaTest.java`

2021-01-28 11:00 UTC, conker84 requested changes

2021-01-28 11:00 UTC, conker84 commented on core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
> +            assertEquals(expectedKeys("baa", "baz"), r.get("keys"));
scusa perché questo è cambiato?

2021-01-28 11:01 UTC, conker84 requested changes

2021-01-28 11:01 UTC, conker84 commented on core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
> +            tx.run("DROP CONSTRAINT ON (f:Foo) ASSERT (f.baa,f.baz) IS NODE KEY").list();
scusa perché questo è cambiato? a linea 138 c'è

2021-01-28 11:20 UTC, vga91 commented on core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
> +            assertEquals(expectedKeys("baa", "baz"), r.get("keys"));
Perché ho aggiunto un altro assert che lo cancella : `testResult(session, "CALL apoc.schema.assert(null,{Foo:[['baa','baz']]})", (result) -> {` a linea 151. 
Questo per controllare che, a differenza del test a linea 143, venga cancellato il vecchio constraint  se è diverso da quello dell'assert, mentre nel testa linea 143 essendo uguale a quello della riga 138 rimane con KEPT.

2021-02-01 12:00 UTC, vga91 commented on core/src/test/java/apoc/schema/SchemasEnterpriseFeaturesTest.java
> +            tx.run("DROP CONSTRAINT ON (f:Foo) ASSERT (f.baa,f.baz) IS NODE KEY").list();
Sì perché ho aggiunto un altro assert: `testResult(session, "CALL apoc.schema.assert(null,{Foo:[['baa','baz']]})", (result) -> {` a linea 151 che va a cancellarlo

2021-02-01 16:26 UTC, closed without merging