Fixes #1784: Add mongo procedure to get record by id
vga91/neo4j-apoc-procedures pull request #28
Opened 2021-01-25 17:43 UTC by vga91

Fixes #1784

2021-01-26 08:34 UTC, conker84 commented on full/src/main/java/apoc/mongodb/MongoDB.java
> +    public Stream<MapResult> byObjectId(@Name("host") String hostOrKey, @Name("db") String db, @Name("collection") String collection, @Name("objectIdValue") String objectIdValue, @Name(value = "field
ottima idea l'uso di config bravissimo

2021-01-26 08:38 UTC, conker84 requested changes
Ottimo solo un piccolo cambiamento grazie mille

2021-01-26 08:38 UTC, conker84 commented on full/src/main/java/apoc/mongodb/MongoDbGetByIdConfig.java
> +public class MongoDbGetByIdConfig {
```suggestion
public class MongoDbConfig {
```

2021-01-26 08:38 UTC, conker84 commented on full/src/main/java/apoc/mongodb/MongoDbGetByIdConfig.java
> +    private final boolean idAsMap;
a questo punto metti il nome del campo id qui dentro ok?

2021-01-28 11:38 UTC, conker84 commented on full/src/test/java/apoc/mongodb/MongoDBTest.java
> +    private static ObjectId nameAsObjectId = new ObjectId("507f191e810c19729de860ea");
che vuol dire questo nome?

2021-01-28 11:38 UTC, conker84 commented on full/src/test/java/apoc/mongodb/MongoDBTest.java
> +    private static ObjectId idAsObjectId = new ObjectId();
come sopra

2021-01-28 11:49 UTC, vga91 commented on full/src/test/java/apoc/mongodb/MongoDBTest.java
> +    private static ObjectId nameAsObjectId = new ObjectId("507f191e810c19729de860ea");
Per indicare un `ObjectId` che viene messo nel campo "name", così da usare la procedura con il config `{fieldName: 'name'}` , invece del default `"_id"`, come nel test a riga 250.
E quello sotto l'ho chiamato analogamente `idAsObjectId`.

2021-02-01 11:37 UTC, conker84 commented
@vga91 puoi fare una prova creando una funzione che ritorna un objectId `apoc.mongodb.objectId` e vedere se funziona con le vecchie?

2021-02-01 16:33 UTC, closed without merging