issue 2930
vga91/neo4j-apoc-procedures pull request #286
Opened 2022-05-24 10:54 UTC by vga91

issue 2930

2022-06-15 08:37 UTC, conker84 requested changes

2022-06-15 08:37 UTC, conker84 commented on core/src/main/java/apoc/export/json/JsonImporter.java
> +                            .filter(c -> c.isConstraintType(ConstraintType.UNIQUENESS))
E le node key???

2022-06-15 13:15 UTC, vga91 commented on core/src/main/java/apoc/export/json/JsonImporter.java
> +                            .filter(c -> c.isConstraintType(ConstraintType.UNIQUENESS))
Ok aggiornato, ho cambiato anche il `noneMatch` successivo perché credo abbia senso verificare una unique/nodeKey che abbia un vincolo di unicità solo sulla proprietà `neo4jImportId`, non su una combinazione di più proprietà.

2022-07-05 16:45 UTC, conker84 commented on core/src/test/java/apoc/export/json/ImportJsonEnterpriseTest.java
> +        session.run("DROP CONSTRAINT userExistence");
```suggestion
        } finally {   
          session.run("DROP CONSTRAINT userExistence");
        }
```

anche negli altri posti

2022-08-02 14:10 UTC, conker84 approved these changes

2022-08-02 14:32 UTC, closed without merging