#1608: improve apoc.ttl to enable deletion of more than 1000 nodes at once
vga91/neo4j-apoc-procedures pull request #3
Opened 2020-08-31 14:10 UTC by vga91

Fixes #1608

One sentence summary of the change.

## Proposed Changes (Mandatory)

A brief list of proposed changes in order to fix the issue:

 - removed limit 1000 to apoc.ttl.expire and apoc.ttl.expireIn
 - added test to apoc.ttl
 - changed `apoc.ttl.expireAtInstant` and `apoc.ttl.expireAfterTimeLength` to `apoc.ttl.expire` and `apoc.ttl.expireIn`

2020-08-31 14:24 UTC, conker84 requested changes

2020-08-31 14:24 UTC, conker84 commented on full/src/main/java/apoc/date/DateExpiry.java
> +	@Procedure(mode = Mode.WRITE, deprecatedBy = "apoc.ttl.expire")
non possiamo cambiare il nome della procedura devi cambiare quello in description

2020-08-31 14:24 UTC, conker84 commented on full/src/main/java/apoc/date/DateExpiry.java
> +	@Procedure(mode = Mode.WRITE, deprecatedBy = "apoc.ttl.expireIn")
come sopra

2020-08-31 14:24 UTC, conker84 commented on full/src/main/java/apoc/ttl/TTLLifeCycle.java
> -            long limit = apocConfig.getInt(ApocConfig.APOC_TTL_LIMIT, 1000);
Ragiona sempre così deve funzionare come "atteso" anche a chi ha già un sistema configurato, se tu gli togli sotto banco questo rischiamo di fare dei danni ok?

2020-08-31 14:24 UTC, conker84 commented on full/src/main/java/apoc/ttl/TTLLifeCycle.java
> -            long limit = apocConfig.getInt(ApocConfig.APOC_TTL_LIMIT, 1000);
quindi qui rimettilo per favore

2020-08-31 14:24 UTC, conker84 commented on full/src/main/java/apoc/ttl/TTLLifeCycle.java
> +            db.executeTransactionally("MATCH (t:TTL) where t.ttl < timestamp() DETACH DELETE t",
qui appendi `LIMIT $limit` solo se l'argomento `limit` è maggiore di 0 ok?

2020-08-31 15:14 UTC, conker84 requested changes

2020-08-31 15:14 UTC, conker84 commented on core/src/main/java/apoc/ApocSettings.java
> +    public static final Setting<Long> apoc_ttl_limit = newBuilder(APOC_TTL_LIMIT, LONG, 0l ).build();
lascia 1000 ma cambialo così
```suggestion
    public static final Setting<Long> apoc_ttl_limit = newBuilder(APOC_TTL_LIMIT, LONG, 0L ).build();
```

2020-08-31 15:14 UTC, conker84 commented on docs/asciidoc/modules/ROOT/pages/config/index.adoc
> +| apoc.ttl.limit=<number> (default: all nodes found) | Maximum number of nodes being deleted in one background transaction
```suggestion
| apoc.ttl.limit=<number> (default: 100) | Maximum number of nodes being deleted in one background transaction, if the value is `0` we exclude the limit
```

2020-08-31 15:14 UTC, conker84 commented on full/src/main/java/apoc/date/DateExpiry.java
> +	@Description("CALL apoc.ttl.expire(node,time,'time-unit') - expire node at specified time by setting :TTL label and `ttl` property")
```suggestion
	@Description("CALL apoc.ttl. expireAtInstant(node,time,'time-unit') - expire node at specified time by setting :TTL label and `ttl` property")
```

Fai attenzione per favore, non avere fretta

2020-08-31 15:14 UTC, conker84 commented on full/src/main/java/apoc/date/DateExpiry.java
> +	@Description("CALL apoc.ttl.expireIn(node,time,'time-unit') - expire node after specified length of time time by setting :TTL label and `ttl` property")
come sopra....

2020-08-31 15:14 UTC, conker84 commented on full/src/main/java/apoc/ttl/TTLLifeCycle.java
> +            db.executeTransactionally("MATCH (t:TTL) where t.ttl < timestamp() WITH t " + ((limit > 0) ? "LIMIT $limit " : "") + "DETACH DELETE t",
```suggestion
            String limit = (limit > 0) ? "LIMIT $limit " : "";
            db.executeTransactionally("MATCH (t:TTL) where t.ttl < timestamp() WITH t " + limit + "DETACH DELETE t",
```

2020-08-31 15:14 UTC, conker84 commented on full/src/test/java/apoc/ttl/TTLTest.java
> +public class TTLTest {
la classe c'è già: è dentro `apoc.date` aggiungi i tuoi test li per favore

2020-08-31 17:48 UTC, conker84 requested changes

2020-08-31 17:48 UTC, conker84 commented on full/src/main/java/apoc/ttl/TTLLifeCycle.java
> -            long limit = apocConfig.getInt(ApocConfig.APOC_TTL_LIMIT, 1000);
@vga91 ti sei dimenticato questo...

2020-09-01 15:37 UTC, jexp commented
we shouldn't change API without backwards compatibility
and we cannot just remove 1000 limit, but if we do it we need to batch changes
we also might need to change it from detach delete to a batched

- delete relationships first with periodic iterate
- then do detach delete on the nodes with periodic iterate

then we can also have a large batch size each e.g. 10k per batch

detach delete is more trick as depending on degree you could delete 1000 nodes and rels or 1000 nodes and 10M rels. which then blows the memory.

2020-09-03 12:50 UTC, conker84 requested changes

2020-09-03 12:50 UTC, conker84 commented on full/src/main/java/apoc/ttl/TTLLifeCycle.java
>                      Util.map("limit", limit),
```suggestion
            String query = "<la query di cancellazione>"
            db.executeTransactionally("CALL apoc.periodic.iterate($query, {params:{limit: $limit}}) YIELD total RETURN total",
                    Util.map("limit", limit, "query", query),
```

2020-09-03 13:48 UTC, conker84 commented on core/src/main/java/apoc/ApocSettings.java
> +    public static final Setting<Long> apoc_ttl_batch_size = newBuilder(APOC_TTL_BATCH_SIZE, LONG, 10000l ).build();
```suggestion
    public static final Setting<Long> apoc_ttl_batch_size = newBuilder(APOC_TTL_BATCH_SIZE, LONG, 10000L ).build();
```

se usi la `l` si confonde con `1` alle volte usa la `L`

2020-09-03 13:48 UTC, conker84 commented on full/src/main/java/apoc/ttl/TTLLifeCycle.java
> +            db.executeTransactionally("CALL apoc.periodic.iterate($queryRels, 'DELETE r', {batchSize: $batchSize, params:{limit: $limit, queryRels: $queryRels}}) YIELD total as relOut\n" +
```suggestion
            db.executeTransactionally("CALL apoc.periodic.iterate($queryRels, 'DELETE r', {batchSize: $batchSize, params:{limit: $limit}}) YIELD total as relOut\n" +
```

2020-09-03 13:48 UTC, conker84 commented on full/src/main/java/apoc/ttl/TTLLifeCycle.java
> +                            "CALL apoc.periodic.iterate($queryNodes, 'DELETE t', {batchSize: $batchSize, params:{limit: $limit, queryNodes: $queryNodes}}) YIELD total RETURN total",
```suggestion
                            "CALL apoc.periodic.iterate($queryNodes, 'DELETE t', {batchSize: $batchSize, params:{limit: $limit}}) YIELD total RETURN total",
```

2020-09-03 13:48 UTC, conker84 commented on full/src/main/java/apoc/ttl/TTLLifeCycle.java
> +                        if (stats.getNodesDeleted() > 0) {
questo non è più valido, dalla query devi farti tornare la count dei nodi e delle relazioni cancellate e usare quella count

2020-09-03 13:48 UTC, conker84 commented on full/src/main/java/apoc/ttl/TTLLifeCycle.java
> +            db.executeTransactionally("CALL apoc.periodic.iterate($queryRels, 'DELETE r', {batchSize: $batchSize, params:{limit: $limit, queryRels: $queryRels}}) YIELD total as relOut\n" +
per favore nodi e relazioni falli con due query separate

2020-09-03 14:53 UTC, conker84 requested changes

2020-09-03 15:12 UTC, conker84 requested changes

2020-09-03 15:12 UTC, conker84 commented on full/src/test/java/apoc/ttl/TTLTest.java
> +        db.shutdown();
non puoi togliere l'annotation `@ClassRule` e fare start/stop dentro ogni metodo?

2020-09-17 10:05 UTC, conker84 approved these changes
@vga91 rimuovi quel commento nel codice per il resto siamo ok

2020-09-17 10:05 UTC, conker84 commented on full/src/test/java/apoc/ttl/TTLTest.java
> + */
togli questo

2020-11-03 17:59 UTC, closed without merging