var fixes with load.html and config browser
vga91/neo4j-apoc-procedures pull request #302
Opened 2022-06-10 13:17 UTC by vga91

var fixes with load.html and config browser

Issues:
- relative urls doesn't recognized
- with file-url not existent the chrome driver doesn't fail.

Changes:
- added tests with relative urls
- removed duplicated `html` file
- moved missing url test in LoadHtmlParameterized

2022-08-01 10:54 UTC, conker84 reviewed
Generalmente va bene, rimuovi la generated-documentation. Una cosa non capisco è la necessita di `MetaItem`, mi puoi spiegare

2022-08-01 10:54 UTC, conker84 commented on core/src/main/java/apoc/util/FileUtils.java
> +        }
non serve

2022-08-01 13:39 UTC, vga91 commented on core/src/main/java/apoc/util/FileUtils.java
> +        }
@conker84 Intendi rimetterlo come prima e non richiamarlo alla riga 140 di `LoadHtmlBrowser.java`, o ho capito male?

2022-08-01 13:42 UTC, vga91 commented
> Generalmente va bene, rimuovi la generated-documentation. Una cosa non capisco è la necessita di `MetaItem`, mi puoi spiegare

@conker84 Era di un altro commit, ora ho aggiornato la `4.4` della fork e si è tolto

2022-08-02 06:51 UTC, conker84 requested changes

2022-08-02 06:51 UTC, conker84 commented on core/src/main/java/apoc/util/FileUtils.java
> +        }
Rimettilo come stava e nell'altro pezzo usa `ApocConfig`

2024-06-25 08:14 UTC, closed without merging