Fixes #1803: `apoc.import.csv` Caused by: java.util.NoSuchElementException: No value present
vga91/neo4j-apoc-procedures pull request #31
Opened 2021-02-08 13:12 UTC by vga91

Fixes #1803

2021-02-09 11:56 UTC, conker84 requested changes

2021-02-09 11:56 UTC, conker84 commented on core/src/test/java/apoc/export/csv/ImportCsvTest.java
> +                        "config", map("delimiter", '|', "ignoreDuplicateNodes", true)
perché hai aggiunto `ignoreDuplicateNodes`?

2021-02-09 13:44 UTC, vga91 commented on core/src/test/java/apoc/export/csv/ImportCsvTest.java
> +                        "config", map("delimiter", '|', "ignoreDuplicateNodes", true)
L'avevo messo così per fare una prova, non mi sono accorto di averlo rimasto. Resettato

2021-02-22 12:39 UTC, conker84 approved these changes
ottimo sottomettilo grazie

2021-02-22 13:51 UTC, closed without merging