[gRNAet7B] Fixes trigger procedures in clusters
vga91/neo4j-apoc-procedures pull request #322
Opened 2022-09-28 12:53 UTC by vga91

Sono partito dalla POC di Nacho, la pr 3183,
ed ho aggiunto i primi tre punti della [card associata](https://trello.com/c/gRNAet7B/1403-fix-apoc-triggers-for-clusters).

Quindi:
- ho splittato `TriggerHandler` (che legge da systemdb, e gestisce `LifecycleAdapter` e `TransactionEventListener`) e `TriggerUtils` (che scrive su system)
- ho deprecato le vecchie procedure, ed ho aggiunto un warning che chiede agli utenti di usare le nuove
- ho aggiunto un controllo per far fallire le le vecchie procedure se vengono eseguite su un FOLLOWER 

----

Con lo split, ho rimosso `ConcurrentHashMap<String, Map<String,Object>> activeTriggers` in quanto adesso leggiamo direttamente dal db di sistema.
Quindi `apoc.trigger.refresh` a questo punto serve solo per fare `registerTransactionEventListener()` e `unregisterTransactionEventListener`.
`TriggerUtils`, in quanto classe Util, ha tutti i metodi statici, in alternativa si potrebbe impostare come classe annotabile con `@Context`, come `TriggerHandler`, ma a quel punto il nome sarebbe fuorviante credo.

Ho cambiato `TriggerTest` rendendolo parametrizzato, per vedere che tra le vecchie procedure e le nuove non ci siano inconsistenze.

Ho rimosso `Class.forName("org.neo4j.kernel.ha.HighlyAvailableGraphDatabase"` in `Util.java`, che non è più presente da neo4j 3.5, infatti dà un `java.lang.ClassNotFoundException: org.neo4j.kernel.ha.HighlyAvailableGraphDatabase`.

2022-10-03 12:33 UTC, conker84 requested changes

2022-10-03 12:33 UTC, conker84 commented on core/src/main/java/apoc/trigger/Trigger.java
> +    @Context public Log log;
Secondo me puoi fare fare anche:
```suggestion
    @Context public Log log;
    
    @Context public DatabaseManagementService dbms;
```

Ed eliminare `ApocConfig#getDatabase`

2022-10-03 12:51 UTC, vga91 commented on core/src/main/java/apoc/trigger/Trigger.java
> +    @Context public Log log;
Purtroppo non va, dice `....DatabaseManagementService is not a known injectable component`

2024-02-27 09:09 UTC, vga91 commented
Trello card closed `https://trello.com/c/gRNAet7B/1403-fix-apoc-triggers-for-clusters`

2024-02-27 09:09 UTC, closed without merging