Issue 2612 review
vga91/neo4j-apoc-procedures pull request #346
Opened 2023-01-24 08:35 UTC by vga91

Riguarda il commento di Michael fatto qui `https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/2704`.

Per fare quello che ha chiesto, 
l'ideale sarebbe stato passare ad esempio un `MapResultType extends Neo4jTypes.MapType` per definire la `UserFunctionSignature` in `Signature.java` (riga 20).
In questo modo [qui](https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/dev/extended/src/main/java/apoc/custom/CypherProceduresHandler.java#L393) non verrebbe fatto il wrapping. 

Però non è possibile perché in `org.neo4j.cypher.internal.spi.procsHelpers` fa una validazione su `Neo4jTypes`.

Quindi ho optato per cambiare l'attributo `category` di `UserFunctionSignature`, che sembra simile all'attributo description e non sembra cambiare il comportamento della funzione.
In questo modo, possiamo distinguere il caso `MAP` da `MAPRESULT`.

---

In alternativa, possiamo semplicemente aggiungere `MAPRESULT` (in Signature.g4) e lasciare il resto così com'è,
e fare in modo si comporti come `STRING` (che a dispetto del nome può ritornare anche interi, mappe, etc..).
Però se faccio `SHOW FUNCTIONS` avrò la signature sbagliata, ovvero con `nomeFun(.... ) :: STRING?`.

---
---

Altrimenti penso sia meglio optare per un parametro aggiuntivo in `apoc.custom.declareFunction(...)` similmente a `forceSingle`

2023-01-30 11:19 UTC, conker84 requested changes
Questa così com'è non va bene, io utilizzerei ANTLR estraendo il return type. Non lo stai sfruttando per niente

2023-01-30 13:27 UTC, vga91 commented
> Questa così com'è non va bene, io utilizzerei ANTLR estraendo il return type. Non lo stai sfruttando per niente

@conker84 
Potrei sbagliarmi, ma credo sia quello che faccio in `Signatures.java` (il `signature.type()` è il tipo di ritorno della firma).
Comunque ora l'ho cambiato un po' ed aggiunto qualche commento.

2023-01-31 10:55 UTC, vga91 commented
@conker84 Cambiato con quanto detto ieri
Ps: la `traceability` è rossa perché non funziona sulle fork

2024-02-29 17:00 UTC, vga91 commented
Fixed `https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/3883`

2024-02-29 17:00 UTC, closed without merging