Fixes #1337: : apoc.truncate
vga91/neo4j-apoc-procedures pull request #38
Opened 2021-03-04 08:21 UTC by vga91

Fixes #1337

2021-03-11 11:47 UTC, conker84 requested changes

2021-03-11 11:47 UTC, conker84 commented on docs/asciidoc/modules/ROOT/pages/overview/apoc.periodic/apoc.periodic.truncate.adoc
> +|config|MAP?|{}
Per favore aggiungi nella documentazione il fatto che supportiamo tutti i parametri di configurazione della apoc.periodic.iterare + `dropSchema`

2021-03-16 14:57 UTC, vga91 commented on docs/asciidoc/modules/ROOT/pages/overview/apoc.periodic/apoc.periodic.truncate.adoc
> +|config|MAP?|{}
L'ho messo nel file `docs/asciidoc/modules/ROOT/partials/usage/config/apoc.periodic.truncate.adoc` che viene richiamato alla riga 28 di questo file.

2021-03-23 14:41 UTC, conker84 commented on docs/asciidoc/modules/ROOT/pages/overview/apoc.periodic/apoc.periodic.truncate.adoc
> +|config|MAP?|{}
oki ottimo!

2021-03-23 14:42 UTC, conker84 approved these changes
ottimo fai l'ultima cosa e sottomettilo

2021-03-23 14:42 UTC, conker84 commented on core/src/main/java/apoc/periodic/Periodic.java
> +    @Procedure(mode = Mode.SCHEMA)
@vga91 per favore aggiungi `@Admin` server per farla eseguire solamente ai profili DBA

2021-03-23 15:54 UTC, closed without merging