Issue 3751: mapParallel2 with rebind error
vga91/neo4j-apoc-procedures pull request #386
Opened 2023-10-09 16:04 UTC by vga91

Issue 3751

L'errore sembra essere dovuto al rebind introdotto in 5.9 (https://github.com/neo4j-contrib/neo4j-apoc-procedures/blob/dev/extended/src/main/java/apoc/cypher/CypherExtended.java#L248).

Sporadicamente il rebind lancia (sottobanco), un:
```
org.neo4j.exceptions.UnderlyingStorageException: Access to record Node[20,used=false,created=false,rel=-1,prop=-1,labels=Inline(0x0:[]),light,fixedRefs=false] went out of bounds of the page. The record size is 15 bytes, and the access was at offset 300 bytes into page 0, and the pages have a capacity of 8192 bytes. The mapped store file in question is /target/test data/neo4j/data/databases/neo4j/neostore.nodestore.db
```

oppure un:
```
org.neo4j.graphdb.NotFoundException: Node 4:cce42f14-8960-44a9-b61f-5cdf5d7f0bc9:420 not found.
```

## Risoluzione

Non sono sicuro se sia un problema di Neo4j o delle Apoc, 
ma per risolverlo possiamo materializzare lo stream che viene parallelizato in seguito, come fatto nella PR.

---

Un'alternativa potrebbe essere inserire un meccanismo di retry, ad esempio:
```
    private <T> T retry(long times, Supplier<T> function) {
        try {
            return function.get();
        } catch (Exception e) {
            System.out.println("e = " + e);
            if (times > 0) {
                return retry(times - 1, function);
            } else {
                throw e;
            }
        }
    }

// ...
 Map<String, Object> retry = retry(5, () -> EntityUtil.anyRebind(tx, next));
 queue.put(new RowResult(row++, retry));
```

## Potenziale problema lato Neo4j

Forse, oltre a fixare il problema lato APOC, varrebbe la pena create una issue su neo4j per verificare se si può risolvere anche lato kernel. Per replicarlo basterebbe creare una procedura tipo:

```
    @Procedure("proc.name")
    public Stream<MapResult> test3(@Name("list") List<Object> data) {
//        List<List<Object>> parallelPartitions = Util.partitionSubList(data, 6, null)
//                .toList();
        Stream<List<Object>> parallelPartitions = Util.partitionSubList(data, 6, null);

        parallelPartitions.forEach((List<Object> partition) -> {
            try (Transaction transaction = db.beginTx();
                 Result result = transaction.execute("UNWIND $part AS part WITH part RETURN part",
                         Map.of("part", data))) {

                result.forEachRemaining(i2 -> {
                    Node part = (Node) i2.get("part");
                    tx.getNodeByElementId(part.getElementId());

//                    EntityUtil.anyRebind(tx, i2);
                });
            }
        });

        return Stream.of();
    }
```
e poi: 
```
UNWIND range(1, $int) as id CREATE (:Polling {id: id})

// maybe 5/6 times..
MATCH (n:Polling) with collect(n) as list 
CALL apoc.cypher.test3(list) 
YIELD value RETURN count(value)
```

2023-10-10 18:10 UTC, conker84 requested changes

2023-10-10 18:10 UTC, conker84 commented on extended/src/main/java/apoc/cypher/CypherExtended.java
> +                    System.out.println("e = " + e);
Questo?

2023-10-11 07:12 UTC, vga91 commented on extended/src/main/java/apoc/cypher/CypherExtended.java
> +                    System.out.println("e = " + e);
Ho fatto una rebase sbagliata, ora l'ho tolto

2023-10-11 07:29 UTC, conker84 commented on extended/src/main/java/apoc/cypher/CypherExtended.java
> +        List<List<Object>> parallelPartitions = Util.partitionSubList(data, (int)(partitions <= 0 ? PARTITIONS : partitions), null)
Secondo me questa non è una risoluzione perché vorrebbe dire ricaricare in memoria i dati...
Prova a scrivere un piccolo documento da condividere con Louise e Nacho per capire se investigare lato db è un'alternativa.
Digli che te l'ho chiesto io.

2023-10-25 15:03 UTC, closed without merging