Issue 3156: apoc.load.csv, failure despite failOnError:false
vga91/neo4j-apoc-procedures pull request #394
Opened 2023-11-20 14:22 UTC by vga91

Issue 3156

- Added `if (failOnError) { throws new RuntimeException(...)}` in CSVSpliterator
- Removed `ignoreErrors` config, which is unused, not documented anywhere, and can get confusing as there is the config `failOnError`.

2023-11-22 08:55 UTC, conker84 reviewed
@vga91 parliamone

2023-11-22 08:55 UTC, conker84 commented on extended/src/main/java/apoc/load/LoadCsv.java
> +        private final boolean failOnError;
Non capisco questo cambiamento, teoricamente il nuovo è la negazione del vecchio....

2023-11-22 09:06 UTC, conker84 requested changes

2023-11-22 09:06 UTC, conker84 commented on extended/src/test/java/apoc/load/LoadCsvTest.java
> +                    assertEquals(2L, row.get("lineNo"));
```suggestion
                    assertEquals(3L, row.get("lineNo"));
```
Dovrebbe essere 3 non due e cosi via i successivi

2023-11-23 08:35 UTC, vga91 commented on extended/src/test/java/apoc/load/LoadCsvTest.java
> +                    assertEquals(2L, row.get("lineNo"));
Cambiato

2024-02-29 15:59 UTC, closed without merging