Added apoc.ttl.enabled.db_name key
vga91/neo4j-apoc-procedures pull request #4
Opened 2020-09-05 12:46 UTC by vga91

Added `apoc.ttl.enabled.db_name=false/true` key to `apoc.conf`.

2020-09-17 09:56 UTC, conker84 requested changes
@vga91 grazie mille per favore vedi i commenti

2020-09-17 09:56 UTC, conker84 commented on full/src/main/java/apoc/ttl/TTLLifeCycle.java
> +        boolean dbEnabled = containsTTLEnabled && apocConfig.getBoolean(apocTTLEnabledDb);
Se fai così si semplifica molto:
```suggestion
        boolean dbEnabled = apocConfig.getConfig().getBoolean(apocTTLEnabledDb, enabled);
```

2020-09-17 09:56 UTC, conker84 commented on full/src/main/java/apoc/ttl/TTLLifeCycle.java
> +        if ( dbEnabled || (enabled && !containsTTLEnabled) ) {
dopo la modifica di sopra a questo punto puoi fare:
```suggestion
        if (dbEnabled) {
```
e accertati di eliminare tutte le variabili inutili

2020-09-17 09:56 UTC, conker84 commented on full/src/test/java/apoc/ttl/TTLClusterTest.java
> +    private static TestcontainersCausalCluster cluster;
il cluster va creato una volta sola dopo di che prima di ogni test pulisci il db.

2020-09-17 09:56 UTC, conker84 commented on full/src/test/java/apoc/ttl/TTLClusterTest.java
> +        assumeFalse(isTravis());
crea tre db diversi dove con ttl attivo globalmente e lo disabiliti su una istanze, verifica che il ttl giri solo dove deve

2020-09-24 12:50 UTC, conker84 requested changes

2020-09-24 12:50 UTC, conker84 commented on full/src/test/java/apoc/ttl/TTLClusterTest.java
> +public class TTLClusterTest {
In realtà ho ragionato che non serve un cluster. Basta un istanza singola di Neo4j e poi vai di multi database

2020-11-03 17:55 UTC, vga91 commented
Duplicated pr

2020-11-03 17:55 UTC, closed without merging