Fixes #1790: Support MongoDB Extended JSON (v2) in apoc.mongodb.* procedures parameters
vga91/neo4j-apoc-procedures pull request #42
Opened 2021-04-01 13:00 UTC by vga91

Fixes #1790

Added `compatibleValues`

2021-04-07 13:02 UTC, conker84 requested changes
considera quanto di sotto, ripensado a quello che mi hai scritto su slack forse ha senso farlo direttamente come #1308 fai il revert implementalo come richiesto da quella issue

2021-04-07 13:02 UTC, conker84 commented on full/src/main/java/apoc/mongodb/MongoDBColl.java
> +                return ((BsonNumber) data).longValue();
questo non va per niente bene:
http://mongodb.github.io/mongo-java-driver/3.8/javadoc/org/bson/BsonNumber.html

è l'interfaccia base per 4 tipi di dato:
BsonDecimal128, BsonDouble, BsonInt32, BsonInt64

per favore leggi sempre prima la documentazione per capire di cosa si tratta

2021-04-07 13:14 UTC, vga91 commented on full/src/main/java/apoc/mongodb/MongoDBColl.java
> +                return ((BsonNumber) data).longValue();
Sì in realtà c'è un po' di incoerenza tra la versione delle apoc e quella documentata. Tipo la `BsonDecimal128` non c'è proprio, non avevo notato che ci fosse anche `BsonDouble` dal codice, avevo visto solo gli int32/64.
Ora lo cambio

2021-05-29 08:18 UTC, conker84 requested changes

2021-05-29 08:18 UTC, conker84 commented on full/src/main/java/apoc/mongodb/MongoDBColl.java
> +                        result.iterator().close();
Uti
```suggestion
                        Util.closeSafetely(result.iterator().close());
```

2021-05-29 08:18 UTC, conker84 commented on full/src/main/java/apoc/mongodb/MongoDBColl.java
> +                        mongoClient.close();
```suggestion
                       Util.closeSafetely(mongoClient.close());
```

2021-05-29 08:18 UTC, conker84 commented on full/src/main/java/apoc/mongodb/MongoDBColl.java
> +        return result.wasAcknowledged() ? result.getDeletedCount() : -result.getDeletedCount();
questo non l'ho capito

2021-05-29 08:18 UTC, conker84 commented on full/src/main/java/apoc/mongodb/MongoDBColl.java
> +                return ((Symbol) data).getSymbol();
per questo c'è un test?

2021-05-29 08:18 UTC, conker84 commented on full/src/main/java/apoc/mongodb/MongoDBUtils.java
> +            }
```suggestion
            Util.closeSafetely(this)
```

2021-05-29 08:45 UTC, conker84 requested changes

2021-05-29 08:45 UTC, conker84 commented on docs/asciidoc/modules/ROOT/pages/database-integration/mongo.adoc
> +| compatibleValues | `Boolean` | true | Converts MongoDB data types into Neo4j data types
io sinceramente questo lo toglierei e lascerei sempre a true, nel senso nelle vecchie procedure dobbiamo continuare a gestirlo, ma nelle nuove non ha senso vorrei fossero sempre ritornati valori di Neo4j

2021-05-29 08:45 UTC, conker84 commented on full/src/main/java/apoc/mongodb/MongoDB.java
>      @Procedure
su tutte queste metti deprecatedBy come fatto [qui](https://github.com/neo4j-contrib/neo4j-apoc-procedures/pull/1878/files) e aggiungi il messagio di deprecation nella Description

2021-05-31 09:31 UTC, vga91 commented on full/src/main/java/apoc/mongodb/MongoDBColl.java
> +                return ((Symbol) data).getSymbol();
Sì, in `assertionsPersonJohn` c'è `sym` che viene creato come `new Symbol("x")`

2021-05-31 10:30 UTC, vga91 commented on full/src/main/java/apoc/mongodb/MongoDBColl.java
> +        return result.wasAcknowledged() ? result.getDeletedCount() : -result.getDeletedCount();
Mmm qui sinceramente sono andato "a fiducia" perché l'ho ripreso dalle procedure vecchie, ma sì in effetti non serve a nulla, farebbe un `" - throw Exception(...)"`

2021-06-03 09:26 UTC, conker84 requested changes

2021-06-03 09:26 UTC, conker84 commented on core/src/main/java/apoc/util/Util.java
> +    public static void closeSafely(Closeable closeable) {
no rimuovi questa e usa quella sopra per favore

2021-06-03 09:26 UTC, conker84 commented on full/src/main/java/apoc/mongodb/Mongo.java
> +                coll -> coll.aggregate(pipeline.stream().map(MongoDBUtils::getDocument).collect(Collectors.toList())).map(MapResult::new),
`pipeline.stream().map(MongoDBUtils::getDocument).collect(Collectors.toList())` me lo metti in una variabile a parte?

2021-06-03 09:26 UTC, conker84 commented on full/src/main/java/apoc/mongodb/Mongo.java
> +        log.error(procedureName + " - uri = '" + uri + "', " + optionalOthers + " config = {" + configString + "}", e);
```suggestion
        log.error(procedureName + " - uri = '" + uri + "', " + optionalOthers + " config = " + JsonUtil.writeValueAsString(config), e);
```

2021-06-04 08:52 UTC, conker84 approved these changes
sottomettilo

2021-06-04 08:59 UTC, closed without merging