Fixes #1824: apoc.nodes.link if not exists
vga91/neo4j-apoc-procedures pull request #44
Opened 2021-04-06 15:13 UTC by vga91

Fixes #1824

Added boolean parameter `checkExistence`, default `false`.

2021-04-07 12:54 UTC, conker84 requested changes

2021-04-07 12:54 UTC, conker84 commented on core/src/main/java/apoc/nodes/Nodes.java
> +    public void link(@Name("nodes") List<Node> nodes, @Name("type") String type, @Name(value = "checkExistence", defaultValue = "false") boolean checkExistence) {
no fallo come configuration param 
```suggestion
    public void link(@Name("nodes") List<Node> nodes, @Name("type") String type, @Name(value = "config", defaultValue = "{}") Map<String, Object> config) {
```

2021-04-07 12:54 UTC, conker84 commented on core/src/main/java/apoc/nodes/Nodes.java
> +    public void link(@Name("nodes") List<Node> nodes, @Name("type") String type, @Name(value = "checkExistence", defaultValue = "false") boolean checkExistence) {
inoltre chiama la proprietà `avoidDuplicates` default false come già hai fatto

2021-04-09 12:03 UTC, conker84 approved these changes

2021-04-09 12:03 UTC, conker84 commented on core/src/main/java/apoc/nodes/Nodes.java
> +                final boolean checkAndNotExists = conf.isAvoidDuplicates() && connected(node, next, type);
ragioniamo un attimo perché abbiamo sempre il solito problema di nomenclatura di variabili e metodi.
Ti devi sempre fare questa domanda: Qual'è la finalità della variabile/metodo?
in questo caso dobbiamo controllare se inserire una relazione:
```suggestion
                final boolean createRelationship = !conf.isAvoidDuplicates() || (conf.isAvoidDuplicates() && !connected(node, next, type));
                if (createRelationship) {
```

2021-04-27 08:06 UTC, conker84 commented on docs/asciidoc/modules/ROOT/partials/usage/apoc.nodes.link.adoc
> +Instead, with CALL apoc.nodes.link(events, "NEXT", {avoidDuplicates: true}) only one relationship of type "NEXT" will remain.
```suggestion
We can check for relationship existence using the `{avoidDuplicates: true}` configuration; calling the previous query twice, 2 relations of type "NEXT" will be created between the nodes, instead, by executing `CALL apoc.nodes.link(events, "NEXT", {avoidDuplicates: true})` only one relationship of type "NEXT" will be created.
```

2021-04-27 08:06 UTC, conker84 commented on core/src/test/java/apoc/nodes/NodesTest.java
> +    private void checkNumberRels(Result result, int numberStartEnd, int numberInnerNode) {
cosa fa questo metodo?

2021-05-10 09:54 UTC, conker84 requested changes

2021-05-10 09:54 UTC, conker84 commented on core/src/test/java/apoc/nodes/NodesTest.java
> +    public void linkWithAvoidDuplicateFalse() {
non ci sono già test che testano il default? non credo questo serva

2021-05-10 09:54 UTC, conker84 commented on core/src/test/java/apoc/nodes/NodesTest.java
> +    public void linkWithAvoidDuplicateTrue() {
questo si può semplificare no?
basta creare un due nodi linkarli la prima volta e poi la seconda volta e vedere quanti nodi ha creato

2021-05-10 14:45 UTC, vga91 commented on core/src/test/java/apoc/nodes/NodesTest.java
> +    public void linkWithAvoidDuplicateFalse() {
C'è solo un test che però fa solo la procedura la prima volta, che è uguale sia con che senza`avoidDuplicates`, senza controllare i duplicati. Comunque ora ho tolto questo ed ho unito al test di sotto

2021-05-10 14:45 UTC, vga91 commented on core/src/test/java/apoc/nodes/NodesTest.java
> +    public void linkWithAvoidDuplicateTrue() {
Ok cambiato

2021-05-17 10:24 UTC, conker84 approved these changes
Perfetto sottomettilo

2021-05-17 13:00 UTC, closed without merging