Fixes #1372: apoc.load.html ability to read runtime structure of the page
vga91/neo4j-apoc-procedures pull request #50
Opened 2021-04-26 07:27 UTC by vga91

- Fixes #1372
- Fixed "baseUri" config
- Moved some tests in `LoadHtmlTestParameterized.java`

2021-05-03 15:20 UTC, conker84 requested changes

2021-05-03 15:20 UTC, conker84 commented on full/src/main/java/apoc/load/LoadHtml.java
> +            Document finalDocument = document;
questo a che serve?

2021-05-03 15:20 UTC, conker84 commented on full/src/main/java/apoc/load/LoadHtml.java
> +            }
Non possiamo mettere uno switch case?

2021-05-03 15:20 UTC, conker84 commented on full/src/main/java/apoc/load/LoadHtml.java
> +                String pageSource = driver.getPageSource();
Non c'è modo di prendere un inputStream?

2021-05-03 15:20 UTC, conker84 commented on full/src/main/java/apoc/load/LoadHtml.java
> +                driver.close();
questo mettilo in un metodo dopo che rifattorizzi come ti chiedo sotto

2021-05-03 15:20 UTC, conker84 commented on full/src/test/resources/html/wikipediaWithJs.html
> +<!DOCTYPE html>
scusa ma sei sicuro che carichi i dati a runtime?

2021-05-03 15:20 UTC, conker84 commented on full/src/test/resources/html/wikipediaWithJs.html
> +<!DOCTYPE html>
se lo apri dal browser che succede?

2021-05-04 16:53 UTC, vga91 commented on full/src/test/resources/html/wikipediaWithJs.html
> +<!DOCTYPE html>
Se lo apro col browser oltre alla struttura statica, mi carica un tag `<strong>` e dei `<td>` che provengono dagli script js.

2021-05-10 10:43 UTC, conker84 requested changes

2021-05-10 10:43 UTC, conker84 commented on full/src/main/java/apoc/load/LoadHtml.java
> +                firefoxOptions.setAcceptInsecureCerts(true);
per favore fai una classe di configurazione e gestisci anche questi parametri

2021-05-17 10:27 UTC, conker84 approved these changes
Fai la piccola cosa sotto e sottomettilo

2021-05-17 10:27 UTC, conker84 commented on full/src/main/java/apoc/load/LoadHtmlConfig.java
> +        this.failSilently = FailSilently.valueOf((String) config.getOrDefault("failSilently", "FALSE"));
```suggestion
        this.failSilently = FailSilently.valueOf((String) config.getOrDefault("failSilently", FailSilently.NAME.toString()));
```

2021-05-17 13:06 UTC, closed without merging