Fixes #1873: Add a validation in apoc.custom.* output/input parameters
vga91/neo4j-apoc-procedures pull request #51
Opened 2021-04-30 07:58 UTC by vga91

Fixes #1873

2021-05-03 16:01 UTC, conker84 requested changes

2021-05-03 16:01 UTC, conker84 commented on full/src/main/java/apoc/custom/CypherProcedures.java
> +        api.executeTransactionally("EXPLAIN " + statement, emptyMap(), result -> {
Ottima idea bravissimo!

2021-05-03 16:01 UTC, conker84 commented on full/src/main/java/apoc/custom/CypherProceduresHandler.java
> +                throw new RuntimeException(ERROR_INVALID_TYPE);
Perché? Io lo lascerei come prima, così è "future-proof"

2021-05-03 16:01 UTC, conker84 commented on full/src/test/java/apoc/custom/SignatureTest.java
> +                try {
era necessario cambiare? se è solo per una question estetica rimettilo come prima

2021-05-03 16:01 UTC, conker84 commented on full/src/main/java/apoc/custom/CypherProcedures.java
> +        }
E duplicato con quello sopra non è il caso di fare un metodo?

2021-05-03 16:01 UTC, conker84 commented on full/src/main/java/apoc/custom/CypherProcedures.java
> +            final boolean outputMismatched = !(defaultOutputs || Set.copyOf(result.columns()).equals(outputSet));
non ho capito questa linea a cosa serve

2021-05-03 16:01 UTC, conker84 commented on full/src/main/java/apoc/custom/CypherProcedures.java
> +            }
cosa stai cercando di fare quì? E' abbastanza contorto

2021-05-03 16:01 UTC, conker84 commented on full/src/main/java/apoc/custom/Signatures.java
> +        return signatureParsed;
Questo è quello sopra secondo me è meglio che li rimettiamo com'erano prima? Non servono se abbiamo la validazione o mi sbaglio?

2021-05-03 16:01 UTC, conker84 commented on full/src/test/java/apoc/custom/CypherProceduresTest.java
> +                "CALL apoc.custom.declareFunction('" + statement + "','RETURN 42 as answer')");
Non è `statement` ma `procedureSignature`?

2021-05-05 09:26 UTC, vga91 commented on full/src/main/java/apoc/custom/Signatures.java
> +        return signatureParsed;
L'ho messo qui perché nel caso di declareFunction/Procedure, è il SignatureParser che se metto dei parametri non validi mi restituisce null, e non posso validare prima che faccia il parse appunto perché senza di esso non posso sapere quali siano gli input/output.
Infatti poi senza questo controllo va in un generico NullPointer, quindi ho messo questo controllo che almeno fa capire che c'è un'errore di sintassi della firma.

2021-05-05 15:54 UTC, vga91 commented on full/src/main/java/apoc/custom/CypherProcedures.java
> +            }
Ho aggiunto un po' di commenti. 
In pratica se dal risultato dell'EXPLAIN vedo che c'è un warning dovuto a parametri mancanti, allora mi estrapolo i parametri mancanti dalla warning e li confronto con quelli inseriti dall'utente. 
Se sono uguali ok, altrimenti vado in errore perché c'è qualcosa che manca

2021-05-05 15:57 UTC, vga91 commented on full/src/test/java/apoc/custom/SignatureTest.java
> +                try {
Sì avendo aggiunto `if (signatureParsed.type() == null)` in `Signature.java` per evitare il NullPointer come ho commentato sotto, ho dovuto cambiare anche qui

2021-05-10 11:46 UTC, conker84 requested changes

2021-05-10 11:46 UTC, conker84 commented on full/src/main/java/apoc/custom/CypherProcedures.java
> +    private void validateInputsAndOutputs(String statement, List<FieldSignature> inputSignatures) {
Just?
```suggestion
    private void validate(String statement, List<FieldSignature> input) {
```

2021-05-10 11:46 UTC, conker84 commented on full/src/main/java/apoc/custom/CypherProcedures.java
> +    private void validateInputsAndOutputs(String statement, List<FieldSignature> inputSignatures, List<FieldSignature> outputSignatures) {
```suggestion
    private void validate(String statement, List<FieldSignature> input, List<FieldSignature> output) {
```

2021-05-10 11:46 UTC, conker84 commented on full/src/main/java/apoc/custom/Signatures.java
> +        return signatureParsed;
Parliamone

2021-05-10 11:46 UTC, conker84 commented on full/src/main/java/apoc/custom/Signatures.java
> -            System.out.println("signature = " + signature);
Ok togliere questo, ma perché togliere il return null?

2021-06-03 09:26 UTC, conker84 requested changes

2021-06-03 09:26 UTC, conker84 commented on full/src/main/java/apoc/custom/CypherProcedures.java
> +        checkForDuplicatedParameters(input, isDefaultInputs, inputSet, ERROR_DUPLICATED_INPUTS);
scusa ma se devi fare il check dei duplicati, non è meglio che il set lo crei una volta dentro il metodo `checkForDuplicatedParameters` 😄

2021-06-03 09:26 UTC, conker84 commented on full/src/main/java/apoc/custom/CypherProcedures.java
> +        });
mettilo in un metodo a parte, scegli un nome SEMPLICE!!!!

2021-06-03 10:24 UTC, vga91 commented on full/src/main/java/apoc/custom/CypherProcedures.java
> +        checkForDuplicatedParameters(input, isDefaultInputs, inputSet, ERROR_DUPLICATED_INPUTS);
Ho fatto così perché `inputSet` e `outputSet` li utilizzo pure più sotto per controllare la coerenza tra i parametri.

2021-06-03 10:24 UTC, vga91 commented on full/src/main/java/apoc/custom/CypherProcedures.java
> +        });
Aggiunto

2021-06-30 07:56 UTC, closed without merging