Fixes #832: Add apoc.redis.* procedures for integratingwith Redis
vga91/neo4j-apoc-procedures pull request #52
Opened 2021-05-11 07:54 UTC by vga91

Fixes #832

2021-05-25 14:52 UTC, conker84 requested changes

2021-05-25 14:52 UTC, conker84 commented on full/src/main/java/apoc/redis/RedisConnection.java
> +        return this.commands.dispatch(CommandType.valueOf(command), cons, commandArgs);
non ho capito a cosa serve

2021-05-25 14:52 UTC, conker84 commented on full/src/test/java/apoc/redis/RedisTest.java
> +        assertEquals(1, getNumConnections());
questo uno non lo puoi valorizzare nella `beforeClass` e poi riutilizzarlo?

2021-05-25 14:52 UTC, conker84 commented on full/build.gradle
> +    compileOnly group: 'io.lettuce', name: 'lettuce-core', version: '6.1.1.RELEASE'
per favore credo manchi la creazione del fat-jar del driver in extra-depencencies

2021-05-25 14:52 UTC, conker84 commented on full/src/main/java/apoc/redis/RedisConnection.java
> +        CommandOutput cons = (CommandOutput) clazz.getConstructor(RedisCodec.class).newInstance(this.codec);
```suggestion
        CommandOutput cons = (CommandOutput) ClassPath.from(Thread.currentThread().getContextClassLoader())
                .getTopLevelClasses(CommandOutput.class.getPackageName())
                .stream()
                .filter(ci -> ci.getName().equalsIgnoreCase(output))
                .findFirst()
                .orElseThrow(() -> new UnsupportedOperationException("Output type not supported: " + output))
                .load()
                .getConstructor(RedisCodec.class)
                .newInstance(this.codec);
```

2021-05-25 14:52 UTC, conker84 commented on full/src/test/java/apoc/redis/RedisTest.java
> +        TestUtil.testCall(db, "CALL apoc.redis.lrange($uri, 'key', 0, 1)", Map.of("uri", URI),
Ha senso che la chiamata la fai dentro la testCall precedente, anche quelli sotto, ma non utilizzando testCall, ma executeTransactionally

2021-05-25 14:52 UTC, conker84 commented on full/src/test/java/apoc/redis/RedisTest.java
> +        TestUtil.testCall(db, "CALL apoc.redis.setGet($uri, 'myKey', 'myValue')", Map.of("uri", URI),
Ma setGet non dovrebbe fare prima la set e poi tornare il risultato? quindi in questo caso io mi aspetto myValue

2021-05-26 10:54 UTC, vga91 commented on full/src/test/java/apoc/redis/RedisTest.java
> +        TestUtil.testCall(db, "CALL apoc.redis.setGet($uri, 'myKey', 'myValue')", Map.of("uri", URI),
Questo metodo ritorna il valore precedente al set, quindi in questo caso null visto che è un nuovo valore

2021-05-27 09:16 UTC, vga91 commented on full/src/main/java/apoc/redis/RedisConnection.java
> +        return this.commands.dispatch(CommandType.valueOf(command), cons, commandArgs);
Per creare dei comandi custom utilizzando il dispatch specificando il tipo di comando e chiavi/valori. Con questa struttura si potrebbero eseguire tutti i comandi del Java Driver senza bisogno i di creare un sacco di procedure/configurazioni, visto che ce ne sono parecchi di comandi

2021-05-27 09:16 UTC, vga91 commented on full/build.gradle
> +    compileOnly group: 'io.lettuce', name: 'lettuce-core', version: '6.1.1.RELEASE'
Aggiunto

2021-05-27 09:20 UTC, vga91 commented on full/src/test/java/apoc/redis/RedisTest.java
> +        TestUtil.testCall(db, "CALL apoc.redis.lrange($uri, 'key', 0, 1)", Map.of("uri", URI),
Non ho capito, intendi fare banalmente `db.executeTransactionally(query)` senza fare le assertion? Ma così testerei solo la prima procedura, o mi sbaglio?

2021-06-09 14:02 UTC, vga91 commented on full/src/main/java/apoc/redis/RedisConnection.java
> +        CommandOutput cons = (CommandOutput) clazz.getConstructor(RedisCodec.class).newInstance(this.codec);
@conker84 Per fare questa cosa, visto che `guava` ha un bug nella versione 20.0,
ho utilizzato la libreria `org.reflections`, che già c'era ma era usata solo per i test.
Adesso l'ho impostata come `compile` , visto che potrebbe essere utilizzata anche in altre procedure,
altrimenti potrei benissimo metterla nelle `extra-dependencies` di redis quando creo il fat jar

2021-06-30 16:06 UTC, conker84 requested changes
fai queste piccole modifiche e sottomettilo

2021-06-30 16:06 UTC, conker84 commented on docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
> +|label:apoc-core[]
revertalo

2021-06-30 16:06 UTC, conker84 commented on docs/asciidoc/modules/ROOT/partials/generated-documentation/nav.adoc
> +*** xref::overview/apoc.bolt/apoc.bolt.load.fromLocal.adoc[]
revertalo

2021-06-30 16:06 UTC, conker84 commented on docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
> +apoc.spatial.sortByDistance(List<Path>) sort the given paths based on the geo informations (lat/long) in ascending order
revert

2021-06-30 16:06 UTC, conker84 commented on docs/asciidoc/modules/ROOT/partials/generated-documentation/documentation.adoc
> +|label:apoc-full[]
revert

2021-06-30 16:06 UTC, conker84 commented on full/src/test/java/apoc/redis/RedisTest.java
> +        return (String) value;
switch/case anche sotto per favore

2021-06-30 16:06 UTC, conker84 commented on full/src/main/java/apoc/redis/RedisConnectionInterface.java
> +public interface RedisConnectionInterface<T> extends AutoCloseable {
```suggestion
public interface IRedisConnection<T> extends AutoCloseable {
```

2021-06-30 16:19 UTC, closed without merging