Fixes #1491: apoc.meta.subgraph returns java.lang.NullPointerException
vga91/neo4j-apoc-procedures pull request #57
Opened 2021-05-17 12:55 UTC by vga91

Fixes #1491, #1906

Fixes #1810 (Still present in `4.0` branch)

2021-05-24 12:43 UTC, conker84 requested changes

2021-05-24 12:43 UTC, conker84 commented on src/main/java/apoc/meta/Meta.java
>              Map<String, Object> entityProperties = new LinkedHashMap<>();
spostalo dopo l'if no?

2021-05-24 12:43 UTC, conker84 commented on src/main/java/apoc/meta/Meta.java
> +        final Iterable<Label> allLabelsInUse = tx.getAllLabelsInUse();
perché questa modifica?

2021-05-24 14:05 UTC, vga91 commented on src/main/java/apoc/meta/Meta.java
> +        final Iterable<Label> allLabelsInUse = tx.getAllLabelsInUse();
Perché questo `allLabelsInUse ` lo uso pure nel `Set<Label> allLabelsAsList` che mi serve filtrare i valori alla riga 420

2021-05-26 12:04 UTC, conker84 requested changes

2021-05-26 12:04 UTC, conker84 commented on src/main/java/apoc/meta/Meta.java
> +                labelNames.stream().filter(labelName -> allLabelsAsSet.contains(Label.label(labelName)));
```suggestion
        Stream<Label> stream = Iterables.stream(this.getAllLabelsInUse());
        if (CollectionUtils.isNotEmpty(labelNames)) {
            stream = stream.filter(rel -> labelNames.contains(rel.name()));
        }
        return stream
                .map(Label::name)
                .collect(toMap(t -> t, ops::nodeLabel));
```

2021-06-28 13:31 UTC, conker84 requested changes

2021-06-28 13:31 UTC, conker84 commented on src/main/java/apoc/meta/Meta.java
>              Map<String, MetaResult> entityData = metaData.get(entityName);
```suggestion
            Map<String, MetaResult> entityData = metaData.getOrDefault(entityName, Collections.emptyMap());
```

2021-06-28 13:31 UTC, conker84 commented on src/main/java/apoc/meta/Meta.java
>              Map<String, MetaResult> entityData = metaData.get(entityName);
secondo me qui andava in nullpointer

2021-06-30 16:09 UTC, conker84 commented
questo mettilo in draft ci devo ragionare se lo possiamo fare

2021-10-25 08:20 UTC, closed without merging