Fixes #1487: apoc.schema.nodes() fails if a fulltext index (node or relationship) is present on multiple labels
vga91/neo4j-apoc-procedures pull request #60
Opened 2021-05-18 10:23 UTC by vga91

TODO : Enterprise Tests

Fixes #1487

2021-06-28 13:35 UTC, conker84 requested changes

2021-06-28 13:35 UTC, conker84 commented on core/src/main/java/apoc/schema/Schemas.java
> +                            Iterable<IndexDescriptor> indexesForRelType = () -> schemaRead.indexesGetForRelationshipType(tokenRead.relationshipType(type));
lo puoi mettere a linea 385?

2021-06-28 13:35 UTC, conker84 commented on core/src/main/java/apoc/schema/Schemas.java
> +        Object relName = labelIds.length > 1 ? IntStream.of(labelIds).boxed().map(tokens::relationshipTypeGetName).sorted().collect(Collectors.toList()) : tokens.relationshipTypeGetName(labelIds[0]);
per favore mettilo in un `if/else`

2021-06-28 13:35 UTC, conker84 commented on core/src/main/java/apoc/schema/Schemas.java
> +            }
spostalo in un metodo

2021-06-29 07:28 UTC, vga91 commented on core/src/main/java/apoc/schema/Schemas.java
> +                            Iterable<IndexDescriptor> indexesForRelType = () -> schemaRead.indexesGetForRelationshipType(tokenRead.relationshipType(type));
No perché dipende dal `type` del Flatmap (`tokenRead.relationshipType(type)`)

2021-06-30 16:21 UTC, conker84 requested changes

2021-06-30 16:21 UTC, conker84 commented on core/src/main/java/apoc/schema/Schemas.java
> +            boolean nodeIndex = definition.isNodeIndex();
scusa ma questo è usato solo nel metodo e gli passi `definition` come argomento! mettilo dentro!

2021-06-30 16:21 UTC, conker84 commented on core/src/test/java/apoc/schema/SchemasTest.java
> +    public void testAssertWithFullTextIndexes() {
non capisco questo test a cosa serve????

2021-07-01 07:52 UTC, vga91 commented on core/src/test/java/apoc/schema/SchemasTest.java
> +    public void testAssertWithFullTextIndexes() {
Per controllare che la `apoc.schema.assert` gestisca anche gli indici fulltext, tramite il metodo `getLabelForAssert(IndexDefinition definition, boolean nodeIndex)`, altrimenti fallirebbe

2021-07-01 08:19 UTC, closed without merging