Fixes #1445: apoc.json.path() returns nulls where it should not
vga91/neo4j-apoc-procedures pull request #63
Opened 2021-05-20 09:23 UTC by vga91

Fixes #1445

2021-05-26 09:25 UTC, conker84 requested changes

2021-05-26 09:25 UTC, conker84 commented on core/src/main/java/apoc/util/JsonUtil.java
> +            Option[] opts = options == null ? defaultJsonPathOptions : options.stream().map(Option::valueOf).toArray(Option[]::new);
```suggestion
            Option[] opts = CollectionUtils.isEmpty(options) ? defaultJsonPathOptions : options.stream().map(Option::valueOf).toArray(Option[]::new);
```

2021-05-26 09:25 UTC, conker84 commented on core/src/main/java/apoc/util/JsonUtil.java
> +            throw new RuntimeException(PATH_OPTIONS_ERROR_MESSAGE);
```suggestion
            throw new RuntimeException(PATH_OPTIONS_ERROR_MESSAGE, e);
```

2021-05-26 09:25 UTC, conker84 commented on core/src/main/java/apoc/util/JsonUtil.java
> +            return (path==null||path.isEmpty()) ? stream  : stream.map((value) -> JsonPath.parse(value, getJsonPathConfig(options)).read(path));
```suggestion
            return StringUtils.isBlank(path) ? stream : stream.map((value) -> JsonPath.parse(value, getJsonPathConfig(options)).read(path));
```

2021-05-31 10:53 UTC, vga91 commented on core/src/main/java/apoc/util/JsonUtil.java
> +            Option[] opts = options == null ? defaultJsonPathOptions : options.stream().map(Option::valueOf).toArray(Option[]::new);
Per come l'ho pensata io, non posso fare così. Per mantenere la compatibilità, ho fatto che se options è nullo allora metto le `defaultJsonPathOptions` (ovvero quelle che ci sono attualmente), mentre se passo un array vuoto semplicemente non passo nessuna opzione aggiuntiva

2021-06-30 16:22 UTC, conker84 commented
Scusa ma non ci sta un modo più semplice?
Abbiamo modificato 41 file per fare cosa?

2021-06-30 16:42 UTC, conker84 commented
ok ho capito

2021-07-01 08:26 UTC, closed without merging