Fixes #1134: allow all apoc.import.* procedure to take binary data instead of a file name/url
vga91/neo4j-apoc-procedures pull request #64
Opened 2021-05-24 13:25 UTC by vga91

Fixes #1134

- TODO: Trigger `DocsTest` when is complete

2021-07-12 16:03 UTC, conker84 requested changes

2021-07-12 16:03 UTC, conker84 commented on core/src/main/java/apoc/export/csv/ImportCsv.java
> +                    final ProgressReporter reporter = new ProgressReporter(null, null, new ProgressInfo(file, source, "csv"));
non capisco questo

2021-07-12 16:03 UTC, conker84 commented on core/src/main/java/apoc/export/csv/ImportCsv.java
> +                        source = "file";
scusami ma è possibile mixare? nel senso passare sia un file che un binario? In questo caso io come source metterei file/binary. Per favore se non c'è aggiungi un test di questa modalità mixed

2021-07-12 16:03 UTC, conker84 commented on core/src/main/java/apoc/load/LoadJson.java
> +    @Description("apoc.load.jsonParams('urlKeyOrBinary',{header:value},payload, config) YIELD value - load from JSON URL (e.g. web-api) while sending headers / payload to import JSON as stream of val
```suggestion
    @Description("apoc.load.jsonParams('urlOrKeyOrBinary',{header:value},payload, config) YIELD value - load from JSON URL (e.g. web-api) while sending headers / payload to import JSON as stream of values if the JSON was an array or a single value if it was a map")
```

2021-07-12 16:03 UTC, conker84 commented on core/src/main/java/apoc/load/LoadJson.java
> +    @Description("apoc.load.jsonParams('urlKeyOrBinary',{header:value},payload, config) YIELD value - load from JSON URL (e.g. web-api) while sending headers / payload to import JSON as stream of val
e aggiorna pure sotto per favore

2021-07-12 16:03 UTC, conker84 commented on core/src/main/java/apoc/export/json/ImportJson.java
> +                        source = "file";
Scusa nell'xml hai giustamente messo `apocConfig.checkReadAllowed(url);` qui no perché?

2021-07-12 16:03 UTC, conker84 commented on core/src/main/java/apoc/export/graphml/ExportGraphML.java
> +                file = (String) fileOrBinary;
Scusa nell'xml hai giustamente messo apocConfig.checkReadAllowed(url); qui no perché?

2021-07-12 16:03 UTC, conker84 commented on core/src/main/java/apoc/export/csv/ImportCsv.java
>                  Util.inThread(pools, () -> {
Scusa nell'xml hai giustamente messo apocConfig.checkReadAllowed(url); qui no perché?

2021-07-12 16:03 UTC, conker84 commented on core/src/main/java/apoc/util/CompressionAlgo.java
> +    private InputStream getInputStream( ByteArrayInputStream stream) throws InstantiationException, IllegalAccessException, InvocationTargetException, NoSuchMethodException {
```suggestion
    private InputStream getInputStream(ByteArrayInputStream stream) throws InstantiationException, IllegalAccessException, InvocationTargetException, NoSuchMethodException {
```

2021-07-12 16:03 UTC, conker84 commented on core/src/main/java/apoc/util/JsonUtil.java
> +            return StringUtils.isEmpty(path) ? stream : stream.map((value) -> JsonPath.parse(value, JSON_PATH_CONFIG).read(path));
```suggestion
            return StringUtils.isBlank(path) ? stream : stream.map((value) -> JsonPath.parse(value, JSON_PATH_CONFIG).read(path));
```

2021-07-12 16:03 UTC, conker84 commented on core/src/test/java/apoc/export/csv/ImportCsvTest.java
> +        final Map<String, Object> config = map("nodeFile", fileToBinary(new File(BASE_URL_FILES, "ignore-nodes.csv"), CompressionAlgo.NONE.name()),
non possiamo farlo compresso? non supportiamo i binari compressi?

2021-07-12 16:03 UTC, conker84 commented on docs/asciidoc/modules/ROOT/pages/import/load-json.adoc
> +| binary | `Enum[BYTES, GZIP, BZIP2, DEFLATE, BLOCK_LZ4, FRAMED_SNAPPY]`` | `null` | If not null, allow to take binary data instead of a file name/url as first parameter.
NONE?

2021-07-12 16:03 UTC, conker84 commented on docs/asciidoc/modules/ROOT/partials/usage/apoc.import.csv.adoc
> +You can also import a file from a binary `byte[]` (not compressed) or a compressed file (allowed compression algos are: `GZIP`, `BZIP2`, `DEFLATE`, `BLOCK_LZ4`, `FRAMED_SNAPPY`).
NONE

2021-07-12 16:03 UTC, conker84 commented on full/src/main/java/apoc/load/LoadCsv.java
> +                throw new RuntimeException("Can't read CSV " + (urlOrBinary instanceof String ? "from URL " + cleanUrl((String) urlOrBinary) : "from binary"), e);
si ma se è un binario `cleanUrl` cosa fa?

2021-07-12 16:03 UTC, conker84 commented on full/src/main/java/apoc/load/LoadCsv.java
> +                throw new RuntimeException("Error reading CSV from " + (url == null ? "binary" : " URL " + cleanUrl(url)) + " at " + lineNo, e);
come sopra

2021-07-12 16:20 UTC, vga91 commented on core/src/main/java/apoc/export/csv/ImportCsv.java
>                  Util.inThread(pools, () -> {
In questo caso il checkReadAllowed viene fatto in `loadNodes()` e `loadRelationships()`,
dove fa `FileUtils.readerFor()` che al suo interno ha `checkReadAllowed`

2021-07-12 16:22 UTC, vga91 commented on core/src/main/java/apoc/export/json/ImportJson.java
> +                        source = "file";
Perché qui viene fatto tramite il `FileUtils.readerFor(..)` che richiama `apocConfig.checkReadAllowed()`

2021-07-12 16:22 UTC, vga91 commented on core/src/main/java/apoc/export/graphml/ExportGraphML.java
> +                file = (String) fileOrBinary;
Come sopra

2021-07-12 16:58 UTC, vga91 commented on core/src/main/java/apoc/export/csv/ImportCsv.java
> +                    final ProgressReporter reporter = new ProgressReporter(null, null, new ProgressInfo(file, source, "csv"));
Qui ho rimasto il ProgressReporter precedente, l'unica cosa è che nel caso di un binario adesso il source è `file/binary` e visto che il primo parametro di quel `ProgressInfo` è il `file`, nel caso di binario, quindi senza file url, ho messo `null`.
Ma vabbè, cambia poco, posso anche resettare `file` per semplicità e lasciare solo `source` come `file` o `file/binary`

2021-07-12 16:59 UTC, vga91 commented on core/src/main/java/apoc/export/csv/ImportCsv.java
> +                        source = "file";
Aggiunto

2021-07-12 17:01 UTC, vga91 commented on full/src/main/java/apoc/load/LoadCsv.java
> +                throw new RuntimeException("Can't read CSV " + (urlOrBinary instanceof String ? "from URL " + cleanUrl((String) urlOrBinary) : "from binary"), e);
Nel caso di binario non fa il `cleanUrl()`, appende solo la stringa `"from binary"`. O intendi altro?

2021-07-12 17:02 UTC, vga91 commented on full/src/main/java/apoc/load/LoadCsv.java
> +                throw new RuntimeException("Error reading CSV from " + (url == null ? "binary" : " URL " + cleanUrl(url)) + " at " + lineNo, e);
Anche qui, nel caso di binario aggiungo solo "binary"

2021-07-13 13:04 UTC, conker84 commented on core/src/main/java/apoc/export/csv/ImportCsv.java
>                  Util.inThread(pools, () -> {
ok

2021-07-19 09:01 UTC, conker84 requested changes

2021-07-19 09:01 UTC, conker84 commented on core/src/main/java/apoc/load/Xml.java
> +        FACTORY.setProperty(XMLInputFactory.IS_COALESCING, true);
non ho capito questo a cosa serve? se lo cambi qui in un qualunque momento lo stai cambiando globalmente... a quest punto conviene metterlo dentro un blocco `static` no=

2021-09-30 15:39 UTC, closed without merging