Fixes #1132: add ability to all export procedures to compress their data
vga91/neo4j-apoc-procedures pull request #70
Opened 2021-06-01 15:35 UTC by vga91

Fixes #1132

[WIP]

2021-07-05 12:20 UTC, conker84 requested changes

2021-07-05 12:20 UTC, conker84 commented on core/src/main/java/apoc/export/csv/CsvFormat.java
> +    public ProgressInfo dump(SubGraph graph, ExportFileManager fileManager, Reporter reporter, ExportConfig config) {
questi cambiamenti non sono necessari rimettili come prima

2021-07-05 12:20 UTC, conker84 commented on core/src/main/java/apoc/export/csv/CsvFormat.java
> +        try (Transaction tx = db.beginTx(); PrintWriter printWriter = writer.getPrintWriter("csv")) {
non cambiamo niente dove non è necessario

2021-07-05 12:20 UTC, conker84 commented on core/src/main/java/apoc/export/csv/CsvFormat.java
> +                    reporter.update(value instanceof Node ? 1: 0,value instanceof Relationship ? 1 : 0, value instanceof Entity ? 0 : 1);
come sopra

2021-07-05 12:20 UTC, conker84 commented on core/src/main/java/apoc/export/cypher/FileManagerFactory.java
> +        int indexOfDot = StringUtils.lastOrdinalIndexOf(fileName, ".", compressionAlgo.equals(CompressionAlgo.NONE) ? 1 : 2);
non ho capito questo

2021-07-05 12:20 UTC, conker84 commented on core/src/main/java/apoc/export/cypher/ExportCypher.java
> +        public Object cleanupStatements;
perché questi?

2021-07-05 12:20 UTC, conker84 commented on core/src/main/java/apoc/util/CompressionAlgo.java
> +    GZIP(GzipCompressorOutputStream.class, GzipCompressorInputStream.class, ".gz"),
non capisco a cosa ti serve l'estensione? se ho un file .pippo ma compresso gz non funziona?

2021-07-05 12:20 UTC, conker84 commented on core/src/main/java/apoc/util/CompressionConfig.java
> +    public CompressionConfig(Map<String, Object> config, String defaultValue) {
```suggestion
    public CompressionConfig(Map<String, Object> config, String defaultCompression) {
```

2021-07-05 14:21 UTC, vga91 commented on core/src/main/java/apoc/export/cypher/FileManagerFactory.java
> +        int indexOfDot = StringUtils.lastOrdinalIndexOf(fileName, ".", compressionAlgo.equals(CompressionAlgo.NONE) ? 1 : 2);
Qui, nel caso di export con file separati, ossia con `bulkImport: true`, come stava prima si prendeva il nome del file rimuovendo dall'ultimo punto, e poi da quel nome creava i vari file, per esempio da `test.uno.due.csv` creava `test.uno.due.nodes.LABEL.csv`, `test.uno.due.relationships.RELTYPE.csv` etc...
Invece nel caso di file compresso, dovendo aggiungere l'estensione della compressione,
passerei da `test.uno.due.csv.gz` a`test.uno.due.nodes.LABEL.csv.gz`, `test.uno.due.relationships.RELTYPE.csv.gz` etc...

2021-07-05 14:22 UTC, vga91 commented on core/src/main/java/apoc/util/CompressionAlgo.java
> +    GZIP(GzipCompressorOutputStream.class, GzipCompressorInputStream.class, ".gz"),
Sì certo, funziona ugualmente, era solo per mettere una validazione, tipo che un `GZIP` doveva avere necessariamente un `.gz`, infatti avevo commentato che era da valutare se serviva o no. Ora l'ho tolgo

2021-07-05 14:25 UTC, vga91 commented on core/src/main/java/apoc/export/cypher/ExportCypher.java
> +        public Object cleanupStatements;
Perché nel caso di export cypher in modalità stream, i risultati non saranno delle stringhe ma dei `byte[]`, come per le altre procedure di export.

2021-09-30 15:55 UTC, conker84 commented on core/src/main/java/apoc/export/cypher/FileManagerFactory.java
> +        int indexOfDot = StringUtils.lastOrdinalIndexOf(fileName, ".", compressionAlgo.equals(CompressionAlgo.NONE) ? 1 : 2);
Ok questo aggiungilo come commento al codice per favore

2021-10-11 10:39 UTC, vga91 commented on core/src/main/java/apoc/export/cypher/FileManagerFactory.java
> +        int indexOfDot = StringUtils.lastOrdinalIndexOf(fileName, ".", compressionAlgo.equals(CompressionAlgo.NONE) ? 1 : 2);
Aggiunto

2021-12-28 15:14 UTC, conker84 approved these changes
Guarda la mia domanda e poi mi sembra di non vedere l'esempio roundtrip, cioé
adesso supportiamo la compressione per export/import fai un test per ogni tipo dove fai l'export e poi l'import e verifica che i dati tornino.

2021-12-28 15:14 UTC, conker84 commented on core/src/main/java/apoc/util/CompressionConfig.java
> +        this.compressionAlgo = (String) config.getOrDefault("compression", defaultCompression);
perché è scomparsa la chiave `COMPRESSION`?

2022-01-03 14:57 UTC, vga91 commented
> Guarda la mia domanda e poi mi sembra di non vedere l'esempio roundtrip, cioé adesso supportiamo la compressione per export/import fai un test per ogni tipo dove fai l'export e poi l'import e verifica che i dati tornino.

@conker84 
Il `COMPRESSION` credo l'abbia tolto per sbaglio dopo una rebase.

Per quanto riguarda il roundtrip, al momento si può fare solo con l'export/import in modalità streaming, quindi poco utile.
Questo perché per come sta adesso nelle procedure di import supportiamo un `byte[]` da poter importare, mentre se importiamo un file, passando come argomento l'url del file dopo facciamo `input instanceof String` (ad esempio in Util.java (riga 369)) ed il comportamento rimane quello di un file "normale". 

Per supportare anche i file compressi, ho modificato il metodo `StreamConnection.toCountingInputStream()`,
però è un po' out-of-scope rispetto alla issue. Nel caso, potrei creare un'altra issue separata e mettere i roundtrip lì dentro.

2022-01-24 14:10 UTC, closed without merging