Fixes #1949: The procedure apoc.export.xls.graph fails with 100+ nodes
vga91/neo4j-apoc-procedures pull request #71
Opened 2021-06-03 14:45 UTC by vga91

- Fixes #1949
- Fixes autosize column with `apoc.export.xls.query(..)`

2021-06-04 08:42 UTC, conker84 requested changes

2021-06-04 08:42 UTC, conker84 commented on full/src/test/java/apoc/export/csv/ExportXlsTest.java
> +    private void assertResults(String fileName, Map<String, Object> r, final String source, boolean test100) {
no
```suggestion
    private void assertResults(String fileName, Map<String, Object> r, final String source, long expectedNodes, long expectedRels) {
```

2021-06-04 08:42 UTC, conker84 commented on full/src/main/java/apoc/export/xls/ExportXls.java
> +            Row row = sheet.rowIterator().next();
questo perché?

2021-06-04 08:42 UTC, conker84 commented on full/src/main/java/apoc/export/xls/ExportXls.java
> +        IntStream.range(0, columnNum).forEach(sheet::autoSizeColumn);
perché?

2021-06-04 08:42 UTC, conker84 commented on full/src/main/java/apoc/export/xls/ExportXls.java
> +        // autoSize when all sizes are kwnown
```suggestion
        // autoSize when all sizes are known
```

2021-06-08 07:57 UTC, vga91 commented on full/src/main/java/apoc/export/xls/ExportXls.java
> +            Row row = sheet.rowIterator().next();
Mi sono accorto che non va bene questo, mi funzionava per un caso fortuito :X, adesso ho cambiato un po' la logica di questa parte

2021-06-08 07:59 UTC, vga91 commented on full/src/main/java/apoc/export/xls/ExportXls.java
> +        IntStream.range(0, columnNum).forEach(sheet::autoSizeColumn);
Perché come stava prima faceva il resize solo quando creava la prima riga ed era sbagliato, perché non si conoscevano ancora tutte le grandezze delle celle.
Non dipende dalla issue, è una cosa che ho trovato facendo un po' di prove

2021-07-01 15:35 UTC, closed without merging