Fixes #1376: apoc.load.csv cannot parse files with backslash character in the data
vga91/neo4j-apoc-procedures pull request #75
Opened 2021-06-08 10:03 UTC by vga91

Fixes #1376

TODO - quando/se si ravviva StackOverflow vedere se il `\` alla fine è un bug o no, e scriverlo in adoc nel caso

2021-09-30 16:05 UTC, conker84 requested changes

2021-09-30 16:05 UTC, conker84 commented on core/src/main/java/apoc/util/Util.java
> +        }
scusa perché questo if? non è out of scope?

2021-10-11 14:21 UTC, vga91 commented on core/src/main/java/apoc/util/Util.java
> +        }
Ho aggiunto il `NONE` per ovviare a casistiche, come nell'esempio della issue, in cui voglio che `VER: AX\GEARBOX\ASSEMBLY` non venga convertito in `VER: AXGEARBOXASSEMBLY`, senza dover specificare un altro carattere non esistente.

2021-10-25 08:18 UTC, conker84 approved these changes
Questo sottomettilo

2021-10-25 08:19 UTC, conker84 commented on core/src/main/java/apoc/util/Util.java
> +        }
@vga91 aggiungilo come commento al codice

2021-10-25 09:41 UTC, closed without merging